dset ^DOMAIN.INFO
title RegCM domain information
options big_endian
undef -9999.
pdef   48   34 lcc   45.39   13.48   24.00   17.00   30.00   60.00   13.48  60000.  60000.
xdef  165 linear   -8.28  0.2703
ydef   77 linear   34.87  0.2703
zdef 1 levels 1000.00
tdef 1 linear 00z01Jan2001 1mo
vars 13
head    0 99 header information        
ht      0 99 surface elevation         
htsd    0 99 surface elevation std. dev
landuse 0 99 surface landuse type      
xlat    0 99 latitude  of cross points 
xlon    0 99 longitude of cross points 
dlat    0 99 latitude  of dot points   
dlon    0 99 longitude of dot points   
xmap    0 99 map factors of cross point
dmap    0 99 map factors of dot points 
coriol  0 99 coriol force              
snowam  0 99 initial snow amount       
mask    0 99 land/sea mask             
endvars
