! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! generated by kpp-2.2 symbolic chemistry kinetics preprocessor
!       (http://www.cs.vt.edu/~asandu/software/kpp)
! kpp is distributed under gpl, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (c) 1995-1997, v. damian & a. sandu, cgrer, univ. iowa
! (c) 1997-2005, a. sandu, michigan tech, virginia tech
!     with important contributions from:
!        m. damian, villanova university, usa
!        r. sander, max-planck institute for chemistry, mainz, germany
! 
! equation file        : gasphs.kpp
! output root filename : gasphs
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

module gasphs_driver

  use mod_constants
  use mod_memutil
  use gasphs_model
  use gasphs_initialize, only: initialize

  private

  integer , parameter :: jo2       =  1
  integer , parameter :: jo31d     =  2
  integer , parameter :: jo33p     =  3
  integer , parameter :: jno2      =  4
  integer , parameter :: jno3a     =  5
  integer , parameter :: jno3b     =  6
  integer , parameter :: jn2o5a    =  7
  integer , parameter :: jn2o5b    =  8
  integer , parameter :: jn2o      =  9
  integer , parameter :: jho2      = 10
  integer , parameter :: jh2o2     = 11
  integer , parameter :: jhno2     = 12
  integer , parameter :: jhno3     = 13
  integer , parameter :: jhno4     = 14
  integer , parameter :: jch2oa    = 15
  integer , parameter :: jch2ob    = 16
  integer , parameter :: jch3choa  = 17
  integer , parameter :: jch3chob  = 18
  integer , parameter :: jch3choc  = 19
  integer , parameter :: jc2h5cho  = 20
  integer , parameter :: jchocho   = 21
  integer , parameter :: jch3cocho = 22
  integer , parameter :: jch3coch3 = 23
  integer , parameter :: jch3ooh   = 24
  integer , parameter :: jch3ono2  = 25
  integer , parameter :: jpan      = 26

  integer :: ich , jch , kch

  real(dp) , pointer , dimension(:) :: taucab , taucbl
  real(dp) , pointer , dimension(:,:,:) :: taucld2
  real(dp) , pointer , dimension(:,:) :: psaa2 , taa2
  real(dp) , pointer , dimension(:) :: hcbl , hcab
  real(dp) , pointer , dimension(:,:,:,:) :: chemall

  public :: allocate_chemistry , chemistry

  contains

    subroutine allocate_chemistry(iy,jx,kz)
      implicit none
      integer , intent(in) :: iy , jx , kz
      ich = iy
      jch = jx
      kch = kz
      call getmem1d(taucab,1,kch,'module_gasphs_driver:taucab')
      call getmem1d(taucbl,1,kch,'module_gasphs_driver:taucbl')
      call getmem3d(taucld2,1,ich,1,kch,1,jch,'module_gasphs_driver:taucld2')
      call getmem2d(psaa2,1,ich,1,kch,'module_gasphs_driver:psaa2')
      call getmem2d(taa2,1,ich,1,kch,'module_gasphs_driver:taa2')
      call getmem1d(hcbl,1,kch,'module_gasphs_driver:hcbl')
      call getmem1d(hcab,1,kch,'module_gasphs_driver:hcab')
      call getmem4d(chemall,1,nvar,1,ich,1,kch, &
                            1,jch-1,'module_gasphs_driver:chemall')
    end subroutine allocate_chemistry

    subroutine chemistry(jj,chem,chemox,jphoto,t_phy,p_phy,zena,ktau,idatein)
      implicit none
      integer , intent(in) :: jj
      integer , intent(in) :: ktau
      integer , intent(in) :: idatein
      real(dp) , dimension(ich) , intent(in) :: zena
      real(dp) , dimension(ich,kch) , intent(in) :: t_phy , p_phy
      real(dp) , dimension(ich,kch,nvar) , intent(in) :: chem 
      real(dp) , dimension(ich,kch,nvar) , intent(out) :: chemox
      real(dp) , dimension(ich,kch,nvar) , intent(out) :: jphoto
!
      real(dp) :: conc_m , prnew
      real(dp) :: t , dval(nspec)
      real(dp) :: rstate(20)
      real(dp) :: levav
      integer :: ntime , i , nn , kk , ii
      integer :: kbl , kab , ll , ic
!
!------------------declaration part for jval----------
!
      integer :: nhv(22) , lsin
      real(dp) :: hvmat(22,40) , hvmatb(22)
      real(dp) :: jarray(80,510,56)
      real(dp) :: jparam(22)
      real(dp) :: jval(56)
      real(dp) :: zen
!
!--------------reading tuvgrid2 part in jval--------------      
!
      lsin = 26
      open(lsin , file='tuvgrid2' , status='old' , position='rewind')
      if ( ktau == 0 ) then
        call readhv(lsin,nhv,hvmat,hvmatb,jarray)
      end if

      stepmin = d_zero
      stepmax = d_zero

      do i = 1 , nvar
        rtol(i) = 1.0d-1!1.0d-4
        atol(i) = 1.0d-1!1.0d-3
      end do

      do kk = 1 , kch
        do ii = 2 , ich-2
          do ic = 1 , 56
            jphoto(ii,kk,ic) = d_zero
          end do
        end do
      end do
      do kk = 1 , kch
        do ii = 2 , ich-2
          ll = kch-kk+1
!         taucld2(ii,ll,jj) = taucld(ii,kk,jj)
          psaa2(ii,ll) = p_phy(ii,kk)
          taa2(ii,ll)  = t_phy(ii,kk)
        end do
      end do

      dt = 3600
      tstart = ktau*dt 
      do kk = kch , 1 , -1       !kk vertical loop
        do ii = 2 , ich-2       !ii horizontal loop
          ll = kk-kch+1
!         do nn=1,nvar
!           var(nn)=0.0
!         end do

!         rconst(227) = 0
!         rconst(228) = 0
!         rconst(229) = 0
!         rconst(230) = 0
          if ( ktau == 0 ) then
            call initialize
          else
            var(ind_o3)    = chem(ii,kk,ind_o3)
            var(ind_no2)   = chem(ii,kk,ind_no2)
            var(ind_no)    = chem(ii,kk,ind_no)
            var(ind_co)    = chem(ii,kk,ind_co)
            var(ind_h2o2)  = chem(ii,kk,ind_h2o2)
            var(ind_hno3)  = chem(ii,kk,ind_hno3) 
            var(ind_n2o5)  = chem(ii,kk,ind_n2o5) 
            var(ind_so2)   = chem(ii,kk,ind_so2)
            var(ind_sulf)  = chem(ii,kk,ind_sulf)
            var(ind_dms)   = chem(ii,kk,ind_dms)
            var(ind_hcho)  = chem(ii,kk,ind_hcho)
            var(ind_ald2)  = chem(ii,kk,ind_ald2)
            var(ind_isop)  = chem(ii,kk,ind_isop)
            var(ind_c2h6)  = chem(ii,kk,ind_c2h6)
            var(ind_c3h8)  = chem(ii,kk,ind_c3h8)
            var(ind_tolu)  = chem(ii,kk,ind_tolu)
            var(ind_xyle)  = chem(ii,kk,ind_xyle)
            var(ind_ethe)  = chem(ii,kk,ind_ethe)
            var(ind_alk4)  = chem(ii,kk,ind_alk4)
            var(ind_alk7)  = chem(ii,kk,ind_alk7)
            var(ind_benz)  = chem(ii,kk,ind_benz)
            var(ind_pan)   = chem(ii,kk,ind_pan)
            var(ind_prpe)  = chem(ii,kk,ind_prpe)
            var(ind_bute)  = chem(ii,kk,ind_bute)
            var(ind_moh)   = chem(ii,kk,ind_moh)
            var(ind_eoh)   = chem(ii,kk,ind_eoh)
            var(ind_ch4)   = chem(ii,kk,ind_ch4)
            var(ind_acet)  = chem(ii,kk,ind_acet)
            var(ind_h2o)   = chem(ii,kk,ind_h2o)
          end if

          temp         = taa2(ii,ll)*d_one
          prnew        = psaa2(ii,ll)
          conc_m       = prnew/(1.380658D-17*temp)
          fix(indf_x)  = conc_m
          c_m          = conc_m

!~~~> time loop

          t = tstart
          tend = tstart+(dt)

          kron: &
          do while (t < tend)
            time = t
            call getmass(c,dval)
            zen = zena(ii)
            jparam(20) = dble(idatein)*d_one
            if (jparam(20) <= 10000.0D0) jparam(20) = jparam(20)+10000.0D0
            jparam(1) = zen !zent(ii) !acosd(sunangl(ii)) !zen
            jparam(2) = prnew*1D-3  !101.5
            jparam(3) = 330.D0
            jparam(4) = 0.1D0
            jparam(5) = 0.1D0
            jparam(6) = 0.38D0
            jparam(7) = 0.85D0
            jparam(8) = 0.1D0
            jparam(9) = 0.D0
            jparam(10)= 0.D0
            jparam(11)= 0.D0
            jparam(12)= 1.D0
            jparam(13)= temp

!           taucab(ll)   = 0.0
!           hcab(ll  )   = 0.0
!           taucbl(ll)   = 0.0
!           hcbl(ll  )   = 0.0
!           if(ll .lt. 18)then
!             do kab=ll+1,18
!               taucab(ll)   = taucab(ll)+taucld2(ii,kab,jj)
!               levav        = 0.5*(psaa2(ii,kab)+psaa2(ii,kab+1))
!               hcab(ll)     = hcab(ll)  + taucld2(ii,kab,jj)*levav
!             end do
!           end if
!           taucab(ll) = taucab(ll) +taucld2(ii,ll,jj)*0.5
!           levav        = 0.5*(psaa2(ii,ll)+psaa2(ii,ll+1))
!           hcab(ll)   = hcab(ll)   + taucld2(ii,ll,jj)*0.5*levav
!           if(taucab(ll) .eq. 0.0 )then
!             hcab(ll) = 0.0
!           else
!             hcab(ll)   = hcab(ll)/taucab(ll)
!           end if
!           if(ll .gt. 1)then
!             do kbl=1,ll-1
!               taucbl(ll)   = taucbl(ll)+taucld2(ii,kbl,jj)
!               levav        = 0.5*(psaa2(ii,kbl)+psaa2(ii,kbl-1))
!               hcbl(ll)     = hcbl(ll)  +taucld2(ii,kbl,jj)*levav
!             end do
!           end if
!           taucbl(ll)   = taucbl(ll) + taucld2(ii,ll,jj)*0.5
!           levav        = 0.5*(psaa2(ii,ll)+psaa2(ii,ll-1))
!           hcbl(ll)   = hcbl(ll)   + taucld2(ii,ll,jj)*0.5*levav
!           if(taucbl(ll) .eq. 0.0 )then
!             hcbl(ll) = 0.0
!           else
!             hcbl(ll)   = hcbl(ll)/taucbl(ll)
!           end if

            call jvalpro(nhv,hvmat,hvmatb,jarray,jparam,jval)

            jval_o31d    =  jval(jo31d)
            jval_no2     =  jval(jno2)*1.5D0
            jval_h2o2    =  jval(jh2o2)
            jval_ch2oa   =  jval(jch2oa)*1.5D0
            jval_ch2ob   =  jval(jch2ob)*1.5D0
            jval_hno3    =  jval(jhno3)
            jval_hno2    =  jval(jhno2)
            jval_hno4    =  jval(jhno4)
            jval_no3a    =  jval(jno3a)
            jval_no3b    =  jval(jno3b)
            jval_n2o5b   =  jval(jn2o5b)
            jval_ch3choa =  jval(jch3choa)
            jval_pan     =  jval(jpan)
            jval_c2h5cho =  jval(jc2h5cho)
            jval_ch3coch3=  jval(jch3coch3)
            jval_chocho  =  jval(jchocho)

            call update_rconst()
            call integrate( tin = t, tout = t+dt, rstatus_u = rstate, &
            icntrl_u = (/ 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 /) )

            t = rstate(1)
!           t=t+dt

          end do kron
!~~~> end time loop
          do nn = 1 , 56
            jphoto(ii,kk,nn) = jval(nn)
          end do

          chemox(ii,kk,ind_oh)    =  var(ind_oh)
          chemox(ii,kk,ind_ho2)   =  var(ind_ho2)
          chemox(ii,kk,ind_h2o)   =  var(ind_h2o)
          chemox(ii,kk,ind_o3)    =  var(ind_o3)
          chemox(ii,kk,ind_no2)   =  var(ind_no2)
          chemox(ii,kk,ind_no)    =  var(ind_no)
          chemox(ii,kk,ind_co)    =  var(ind_co)
          chemox(ii,kk,ind_h2o2)  =  var(ind_h2o2)
          chemox(ii,kk,ind_hno3)  =  var(ind_hno3)
          chemox(ii,kk,ind_n2o5)  =  var(ind_n2o5)
          chemox(ii,kk,ind_so2)   =  var(ind_so2)
          chemox(ii,kk,ind_sulf)  =  var(ind_sulf)
          chemox(ii,kk,ind_dms)   =  var(ind_dms)
          chemox(ii,kk,ind_hcho)  =  var(ind_hcho)
          chemox(ii,kk,ind_ald2)  =  var(ind_ald2)
          chemox(ii,kk,ind_isop)  =  var(ind_isop)
          chemox(ii,kk,ind_c2h6)  =  var(ind_c2h6)
          chemox(ii,kk,ind_c3h8)  =  var(ind_c3h8)
          chemox(ii,kk,ind_tolu)  =  var(ind_tolu)
          chemox(ii,kk,ind_xyle)  =  var(ind_xyle)
          chemox(ii,kk,ind_ethe)  =  var(ind_ethe)
          chemox(ii,kk,ind_alk4)  =  var(ind_alk4)
          chemox(ii,kk,ind_alk7)  =  var(ind_alk7)
          chemox(ii,kk,ind_benz)  =  var(ind_benz)
          chemox(ii,kk,ind_pan)   =  var(ind_pan)
          chemox(ii,kk,ind_prpe)  =  var(ind_prpe)
          chemox(ii,kk,ind_bute)  =  var(ind_bute)
          chemox(ii,kk,ind_moh)   =  var(ind_moh)
          chemox(ii,kk,ind_eoh)   =  var(ind_eoh)
          chemox(ii,kk,ind_ch4)   =  var(ind_ch4)
          chemox(ii,kk,ind_acet)  =  var(ind_acet)
        end do !ii loop
      end do !kk loop

      write(*,555) ktau*100 , minval(chemox(2:ich-2,kch,ind_o3)),   &
                              maxval(chemox(2:ich-2,kch,ind_oh)),   &
                              maxval(chemox(2:ich-2,kch,ind_hcho)), &
                              maxval(chemox(2:ich-2,kch,ind_no)),   &
!                             maxval(jphoto(2:ich-2,kch,jno2)),     &
                              jj
      time = t
      close(lsin)

555  format(i5,5x,4(1pe10.3,2x),i2)

    end subroutine chemistry

end module gasphs_driver
