! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.2 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gasphs_Monitor.f90
! Time                 : Tue Mar 10 15:03:35 2009
! Working directory    : /scratch/ASHALABY/KPP/COMPARE/SILLMAN
! Equation file        : gasphs.kpp
! Output root filename : gasphs
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gasphs_Monitor


  CHARACTER(LEN=12), PARAMETER, DIMENSION(90) :: SPC_NAMES_0 = (/ &
     'SULF        ','MAO2        ','CO2         ', &
     'H2          ','C3H8        ','IPAN        ', &
     'BENZ        ','XYLE        ','GPAN        ', &
     'TOLU        ','CH4         ','N2O5        ', &
     'ADI         ','ACHO        ','ADBP        ', &
     'ARP         ','C2H6        ','ALK4        ', &
     'ALK7        ','A3N2        ','PINT        ', &
     'NITP        ','R7O1        ','HACO        ', &
     'CRES        ','DMP         ','H2O2        ', &
     'ISNP        ','HONO        ','HNO4        ', &
     'PAN         ','R7N2        ','PPN         ', &
     'APAN        ','DPAN        ','YPAN        ', &
     'ZPAN        ','PBZN        ','RCOH        ', &
     'MP          ','ETP         ','RA3P        ', &
     'RB3P        ','R4P         ','R7P         ', &
     'MAP         ','EP          ','PP          ', &
     'RP          ','GP          ','ADTP        ', &
     'ADXP        ','AD2P        ','BAP         ', &
     'PHP         ','BUP         ','DMS         ', &
     'XPAN        ','AHO2        ','AP          ', &
     'DAP         ','XAP         ','YAP         ', &
     'ZAP         ','R3N1        ','ETHE        ', &
     'ISNT        ','DIAL        ','ADDB        ', &
     'ARO2        ','PHEN        ','IPRD        ', &
     'R6N1        ','R5N1        ','H2O         ', &
     'SO2         ','ADAL        ','MAOP        ', &
     'YCO2        ','AO1         ','DCO2        ', &
     'ZCO2        ','XCO2        ','MPAN        ', &
     'ACO2        ','MDAL        ','ADD2        ', &
     'PRPN        ','R7N1        ','VRP         ' /)
  CHARACTER(LEN=12), PARAMETER, DIMENSION(86) :: SPC_NAMES_1 = (/ &
     'IAP         ','PIP         ','LIP         ', &
     'ACET        ','APIN        ','INPN        ', &
     'LIMO        ','PRPE        ','MRP         ', &
     'ISOP        ','MVNP        ','ACTA        ', &
     'PHO2        ','PIN2        ','CO          ', &
     'AO0         ','DCO1        ','ZCO1        ', &
     'RIP         ','YCO1        ','XCO1        ', &
     'EOH         ','ROH         ','CHO2        ', &
     'CRO2        ','EO2         ','GCO3        ', &
     'MOH         ','A3O2        ','B3O2        ', &
     'R4N1        ','BUO2        ','BCO3        ', &
     'POXY        ','HNO3        ','MAN2        ', &
     'ADDT        ','ADDX        ','ZCO3        ', &
     'DCO3        ','XCO3        ','YCO3        ', &
     'AO2         ','GLYX        ','R7O2        ', &
     'MVN2        ','RCO3        ','PO2         ', &
     'PIO2        ','LIO2        ','IALD        ', &
     'PRN1        ','INO2        ','R4O2        ', &
     'ATO2        ','BUTE        ','MEK         ', &
     'ALD2        ','HAC         ','R4N2        ', &
     'MVN1        ','HCHO        ','IAO2        ', &
     'MGLY        ','KO2         ','ETO2        ', &
     'RIO1        ','ISNR        ','GLYC        ', &
     'RCHO        ','MACR        ','MAO3        ', &
     'NO2         ','MVK         ','NO3         ', &
     'MO2         ','HO2         ','MCO3        ', &
     'RIO2        ','IPO2        ','VRO2        ', &
     'OH          ','O3          ','MRO2        ', &
     'NO          ','x           ' /)
  CHARACTER(LEN=12), PARAMETER, DIMENSION(176) :: SPC_NAMES = (/&
    SPC_NAMES_0, SPC_NAMES_1 /)

  INTEGER, PARAMETER, DIMENSION(3) :: LOOKAT = (/ &
       1, 76,173 /)

  INTEGER, PARAMETER, DIMENSION(2) :: MONITOR = (/ &
     163,175 /)

  CHARACTER(LEN=12), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '    O3 + NO --> NO2                                                                                 ', &
     '    OH + O3 --> HO2                                                                                 ', &
     '   HO2 + O3 --> OH                                                                                  ', &
     '   NO2 + O3 --> NO3                                                                                 ', &
     '   MO2 + O3 --> HCHO + HO2                                                                          ', &
     '       2 OH --> O3                                                                                  ', &
     '       2 OH --> H2O2                                                                                ', &
     '   HO2 + OH -->                                                                                     ', &
     '  H2O2 + OH --> HO2                                                                                 ', &
     '   HO2 + NO --> NO2 + OH                                                                            ', &
     '      2 HO2 --> H2O2                                                                                ', &
     '    H2 + OH --> HO2                                                                                 ', &
     '    CO + OH --> HO2                                                                                 ', &
     '   CH4 + OH --> MO2                                                                                 ', &
     '   MO2 + NO --> HCHO + NO2 + HO2                                                                    ', &
     '  MO2 + HO2 --> MP                                                                                  ', &
     '  MO2 + HO2 --> HCHO                                                                                ', &
     '      2 MO2 --> MOH + HCHO                                                                          ', &
     '      2 MO2 --> 2 HCHO + 2 HO2                                                                      ', &
     '    MP + OH --> 0.3 HCHO + 0.7 MO2 + 0.3 OH                                                         ', &
     '  HCHO + OH --> CO + HO2                                                                            ', &
     '   NO2 + OH --> HNO3                                                                                ', &
     '  HNO3 + OH --> NO3                                                                                 ', &
     '    OH + NO --> HONO                                                                                ', &
     '  HONO + OH --> NO2                                                                                 ', &
     '  NO2 + HO2 --> HNO4                                                                                ', &
     '   HNO4 + x --> NO2 + HO2 + x                                                                       ', &
     '  HNO4 + OH --> NO2                                                                                 ', &
     '  NO3 + HO2 --> NO2 + OH                                                                            ', &
     '   NO3 + NO --> 2 NO2                                                                               ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '   NO3 + OH --> NO2 + HO2                                                                           ', &
     '  NO2 + NO3 --> N2O5                                                                                ', &
     '   N2O5 + x --> NO2 + NO3 + x                                                                       ', &
     '  ACO2 + OH --> CO2 + HO2                                                                           ', &
     '   MOH + OH --> HCHO + HO2                                                                          ', &
     '  NO2 + NO3 --> NO2 + NO                                                                            ', &
     ' HCHO + NO3 --> CO + HNO3 + HO2                                                                     ', &
     '  ALD2 + OH --> MCO3                                                                                ', &
     ' ALD2 + NO3 --> HNO3 + MCO3                                                                         ', &
     ' NO2 + MCO3 --> PAN                                                                                 ', &
     '    PAN + x --> NO2 + MCO3 + x                                                                      ', &
     '  MCO3 + NO --> NO2 + MO2                                                                           ', &
     '  C2H6 + OH --> ETO2                                                                                ', &
     '  ETO2 + NO --> ALD2 + NO2 + HO2                                                                    ', &
     '  C3H8 + OH --> B3O2                                                                                ', &
     '  C3H8 + OH --> A3O2                                                                                ', &
     '  A3O2 + NO --> RCHO + NO2 + HO2                                                                    ', &
     '   PO2 + NO --> ALD2 + HCHO + NO2 + HO2                                                             ', &
     '  ALK4 + OH --> R4O2                                                                                ', &
     '  R4O2 + NO --> 0.32 ACET + 0.05 A3O2 + 0.18 B3O2 + 0.19 MEK + 0.32 ALD2 ... etc.                   ', &
     '  R4O2 + NO --> R4N2                                                                                ', &
     '  R4N1 + NO --> 0.3 R4O2 + 0.75 ALD2 + 0.39 HCHO + 0.57 RCHO + 2 NO2 ... etc.                       ', &
     '  ATO2 + NO --> 0.04 A3N2 + 0.96 HCHO + 0.96 NO2 + 0.96 MCO3                                        ', &
     '   KO2 + NO --> 0.07 A3N2 + 0.93 ALD2 + 0.93 NO2 + 0.93 MCO3 + 0.93 NO ... etc.                     ', &
     '  RIO2 + NO --> 0.127 IALD + 0.69 HCHO + 0.136 RIO1 + 0.288 MACR + NO2 ... etc.                     ', &
     '  RIO2 + NO --> ISNT                                                                                ', &
     '  RIO1 + NO --> IALD + 0.75 HCHO + NO2 + HO2                                                        ', &
     '  RIO1 + NO --> ISNT                                                                                ', &
     '  IAO2 + NO --> 0.61 CO + 0.08 HNO3 + 0.33 HAC + 0.35 HCHO + 0.53 MGLY ... etc.                     ', &
     '  MVN1 + NO --> 0.05 HNO3 + 0.95 HAC + 0.95 GLYC + 1.95 NO2                                         ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '  VRO2 + NO --> 0.28 HCHO + 0.28 MGLY + 0.72 GLYC + NO2 + 0.28 HO2 + 0.72 MCO3 ... etc.             ', &
     '  VRO2 + NO --> ISNT                                                                                ', &
     '  MRO2 + NO --> 0.83 CO + 0.83 HAC + 0.17 HCHO + 0.17 MGLY + NO2 + HO2 ... etc.                     ', &
     '  MRO2 + NO --> ISNT                                                                                ', &
     '  MVN2 + NO --> 0.1 HNO3 + 0.3 HCHO + 0.3 MGLY + 0.6 GLYC + 1.9 NO2 ... etc.                        ', &
     '  MAN2 + NO --> HCHO + MGLY + 2 NO2                                                                 ', &
     '  B3O2 + NO --> ACET + NO2 + HO2                                                                    ', &
     '  INO2 + NO --> 0.85 ISNT + 0.15 HCHO + 0.1 MACR + 1.15 NO2 + 0.05 MVK ... etc.                     ', &
     '  PRN1 + NO --> ALD2 + HCHO + 2 NO2                                                                 ', &
     ' ALK4 + NO3 --> HNO3 + R4O2                                                                         ', &
     '  R4N2 + OH --> R4N1                                                                                ', &
     '  ACTA + OH --> CO2 + MO2                                                                           ', &
     '  RCHO + OH --> RCO3                                                                                ', &
     ' RCO3 + NO2 --> PPN                                                                                 ', &
     ' GCO3 + NO2 --> GPAN                                                                                ', &
     ' MAO3 + NO2 --> MPAN                                                                                ', &
     '    PPN + x --> RCO3 + NO2 + x                                                                      ', &
     '   GPAN + x --> GCO3 + NO2 + x                                                                      ', &
     '  RCO3 + NO --> ETO2 + NO2                                                                          ', &
     '  GCO3 + NO --> HCHO + NO2 + HO2                                                                    ', &
     '  MAO3 + NO --> 4 HCHO + NO2 + HO2                                                                  ', &
     ' RCHO + NO3 --> HNO3 + RCO3                                                                         ', &
     '  ACET + OH --> ATO2                                                                                ', &
     ' A3O2 + MO2 --> 0.25 ROH + 0.25 MOH + 0.75 HCHO + 0.75 RCHO + HO2                                   ', &
     '  PO2 + MO2 --> 0.25 ROH + 0.25 MOH + 0.5 ALD2 + 0.16 HAC + 1.25 HCHO ... etc.                      ', &
     ' R4O2 + HO2 --> R4P                                                                                 ', &
     ' R4N1 + HO2 --> R4N2                                                                                ', &
     ' ATO2 + HO2 --> MO2 + MCO3                                                                          ', &
     '  KO2 + HO2 --> MGLY + MO2                                                                          ', &
     ' HO2 + RIO2 --> RIP                                                                                 ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_3 = (/ &
     ' RIO1 + HO2 --> RIP                                                                                 ', &
     ' IAO2 + HO2 --> IAP                                                                                 ', &
     ' MVN1 + HO2 --> MVNP                                                                                ', &
     ' HO2 + VRO2 --> VRP                                                                                 ', &
     ' HO2 + MRO2 --> MRP                                                                                 ', &
     ' MVN2 + HO2 --> MVNP                                                                                ', &
     ' MAN2 + HO2 --> MVNP                                                                                ', &
     ' B3O2 + HO2 --> RB3P                                                                                ', &
     ' INO2 + HO2 --> INPN                                                                                ', &
     ' PRN1 + HO2 --> PRPN                                                                                ', &
     '   MEK + OH --> KO2                                                                                 ', &
     ' ETO2 + MO2 --> 0.25 EOH + 0.25 MOH + 0.75 ALD2 + 0.75 HCHO + HO2                                   ', &
     '  MEK + NO3 --> HNO3 + KO2                                                                          ', &
     ' R4O2 + MO2 --> 0.16 ACET + 0.25 ROH + 0.25 MOH + 0.03 A3O2 + 0.09 B3O2 ... etc.                    ', &
     ' R4N1 + MO2 --> 0.25 ROH + 0.25 MOH + 0.15 R4O2 + 0.38 ALD2 + 0.95 HCHO ... etc.                    ', &
     ' ATO2 + MO2 --> 0.5 MOH + 0.2 HAC + 0.5 HCHO + 0.5 MGLY + 0.3 HO2 + 0.3 MCO3 ... etc.               ', &
     '  KO2 + MO2 --> 0.25 ROH + 0.25 MOH + 0.25 MEK + 0.5 ALD2 + 0.75 HCHO ... etc.                      ', &
     ' MO2 + RIO2 --> 0.25 ROH + 0.25 MOH + 0.06 IALD + 0.25 MEK + HCHO + 0.07 RIO1 ... etc.              ', &
     ' RIO1 + MO2 --> 0.25 ROH + 0.25 MOH + 0.5 IALD + 0.25 MEK + 1.03 HCHO ... etc.                      ', &
     ' IAO2 + MO2 --> 0.33 CO + 0.25 ROH + 0.25 MOH + 0.25 MEK + 0.18 HAC ... etc.                        ', &
     ' MVN1 + MO2 --> 0.25 ROH + 0.25 MOH + 0.5 HAC + 0.75 HCHO + 0.5 GLYC ... etc.                       ', &
     ' MO2 + VRO2 --> 0.25 ROH + 0.25 MOH + 0.25 MEK + 0.89 HCHO + 0.14 MGLY ... etc.                     ', &
     ' MO2 + MRO2 --> 0.42 CO + 0.25 ROH + 0.25 MOH + 0.25 MEK + 0.42 HAC ... etc.                        ', &
     ' MVN2 + MO2 --> 0.25 ROH + 0.25 MOH + 1.25 HCHO + 0.25 MGLY + 0.25 RCHO ... etc.                    ', &
     ' MAN2 + MO2 --> 0.25 ROH + 0.25 MOH + 1.25 HCHO + 0.5 MGLY + 0.25 RCHO ... etc.                     ', &
     ' B3O2 + MO2 --> 0.75 ACET + 0.25 ROH + 0.25 MOH + 0.75 HCHO + HO2                                   ', &
     ' INO2 + MO2 --> 0.25 ROH + 0.25 MOH + 0.425 HNO3 + 0.83 HCHO + 0.25 RCHO ... etc.                   ', &
     ' PRN1 + MO2 --> 0.25 ROH + 0.25 MOH + 0.5 ALD2 + 1.25 HCHO + 0.25 RCHO ... etc.                     ', &
     '   EOH + OH --> ALD2 + HO2                                                                          ', &
     '   ROH + OH --> RCHO + HO2                                                                          ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_4 = (/ &
     '     2 ETO2 --> 0.4 EOH + 1.6 ALD2 + 1.2 HO2                                                        ', &
     ' ETO2 + HO2 --> ETP                                                                                 ', &
     ' A3O2 + HO2 --> RA3P                                                                                ', &
     '  PO2 + HO2 --> PP                                                                                  ', &
     ' HO2 + MCO3 --> ACTA + O3                                                                           ', &
     ' HO2 + MCO3 --> MAP                                                                                 ', &
     ' RCO3 + HO2 --> 0.3 RCOH + 0.7 RP + 0.3 O3                                                          ', &
     ' GCO3 + HO2 --> 0.3 RCOH + 0.7 GP + 0.3 O3                                                          ', &
     ' MAO3 + HO2 --> 0.3 RCOH + 0.7 MAOP + 0.3 O3                                                        ', &
     '  PRPE + OH --> PO2                                                                                 ', &
     '  PRPE + O3 --> 0.42 CO + 0.5 ALD2 + 0.535 HCHO + 0.305 MO2 + 0.3 HO2 ... etc.                      ', &
     '   MPAN + x --> MAO3 + NO2 + x                                                                      ', &
     '  MPAN + OH --> 0.59 HAC + 2.23 HCHO + NO2 + 2 HO2                                                  ', &
     '  MPAN + O3 --> 0.6 HCHO + NO2 + HO2                                                                ', &
     '  GLYC + OH --> 0.8 GCO3 + 0.2 GLYX + 0.2 HO2                                                       ', &
     ' PRPE + NO3 --> PRN1                                                                                ', &
     '  GLYX + OH --> 2 CO + HO2                                                                          ', &
     '  MGLY + OH --> CO + MCO3                                                                           ', &
     ' GLYX + NO3 --> 2 CO + HNO3 + HO2                                                                   ', &
     ' MGLY + NO3 --> CO + HNO3 + MCO3                                                                    ', &
     '  ISOP + OH --> RIO2                                                                                ', &
     '   MVK + OH --> VRO2                                                                                ', &
     '  MACR + OH --> 0.5 MAO3 + 0.5 MRO2                                                                 ', &
     '   HAC + OH --> MGLY + HO2                                                                          ', &
     'A3O2 + MCO3 --> RCHO + MO2 + HO2                                                                    ', &
     'A3O2 + MCO3 --> ACTA + RCHO                                                                         ', &
     ' PO2 + MCO3 --> ALD2 + HCHO + MO2 + HO2                                                             ', &
     ' PO2 + MCO3 --> ACTA + 0.65 HAC + 0.35 RCHO                                                         ', &
     '  ISOP + O3 --> 0.275 CO + 0.15 EOH + 0.204 MOH + 0.1 HAC + 0.592 HCHO ... etc.                     ', &
     '   MVK + O3 --> 0.05 CO + 0.04 ALD2 + 0.8 HCHO + 0.82 MGLY + 0.06 HO2 ... etc.                      ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_5 = (/ &
     '  MACR + O3 --> 0.2 CO + 0.7 HCHO + 0.8 MGLY + 0.275 HO2 + 0.215 OH ... etc.                        ', &
     ' ISOP + NO3 --> INO2                                                                                ', &
     '  MVK + NO3 --> MVN2                                                                                ', &
     ' MACR + NO3 --> 0.33 HNO3 + 0.67 MAN2 + 0.33 MAO3                                                   ', &
     ' RCO3 + MO2 --> HCHO + ETO2 + HO2                                                                   ', &
     ' GCO3 + MO2 --> 2 HCHO + 2 HO2                                                                      ', &
     ' MAO3 + MO2 --> 2 HCHO + HO2 + MCO3                                                                 ', &
     ' RCO3 + MO2 --> RCOH + HCHO                                                                         ', &
     ' GCO3 + MO2 --> RCOH + HCHO                                                                         ', &
     ' MAO3 + MO2 --> RCOH + HCHO                                                                         ', &
     '  INPN + OH --> INO2                                                                                ', &
     '  PRPN + OH --> PRN1                                                                                ', &
     '   ETP + OH --> 0.5 ALD2 + 0.5 ETO2 + 0.5 OH                                                        ', &
     '  RA3P + OH --> 0.5 A3O2 + 0.5 RCHO + 0.5 OH                                                        ', &
     '  RB3P + OH --> 0.5 B3O2 + 0.5 RCHO + 0.5 OH                                                        ', &
     '   R4P + OH --> 0.5 R4O2 + 0.5 RCHO + 0.5 OH                                                        ', &
     '    RP + OH --> 0.5 RCO3 + 0.5 ALD2 + 0.5 OH                                                        ', &
     '    PP + OH --> 0.5 PO2 + 0.5 RCHO + 0.5 OH                                                         ', &
     '    GP + OH --> 0.5 GCO3 + 0.5 HCHO + 0.5 OH                                                        ', &
     '   RIP + OH --> 0.5 IAO2 + 0.2 RIO1 + 0.4 RIO2                                                      ', &
     '   IAP + OH --> 0.335 CO + 0.18 HAC + 0.5 IAO2 + 0.29 MGLY + 0.13 GLYC ... etc.                     ', &
     '  MVNP + OH --> 0.5 MVN1 + 0.5 MGLY + 0.5 NO2 + 0.5 OH                                              ', &
     '   VRP + OH --> 0.14 HCHO + 0.5 MGLY + 0.36 GLYC + 0.5 VRO2 + 0.5 OH ... etc.                       ', &
     '   MRP + OH --> 0.415 CO + 0.415 HAC + 0.085 HCHO + 0.085 MGLY + 0.5 OH ... etc.                    ', &
     '  MAOP + OH --> HCHO + 0.5 MAO3 + 0.5 OH                                                            ', &
     '   MAP + OH --> 0.5 HCHO + 0.5 MCO3 + 0.5 OH                                                        ', &
     '  INPN + O3 --> HCHO + 0.667 MACR + NO2 + 0.333 MVK                                                 ', &
     '  PRPN + O3 --> ALD2 + HCHO + NO2                                                                   ', &
     '   RIP + O3 --> 0.127 IALD + 0.69 HCHO + 0.136 RIO1 + 0.288 MACR + 0.402 MVK ... etc.               ', &
     '   IAP + O3 --> 0.67 CO + 0.36 HAC + 0.58 MGLY + 0.26 GLYC                                          ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_6 = (/ &
     '  MVNP + O3 --> MGLY + NO2                                                                          ', &
     '   VRP + O3 --> 0.28 HCHO + MGLY + 0.72 GLYC                                                        ', &
     '   MRP + O3 --> 0.83 CO + 0.83 HAC + 0.17 HCHO + 0.17 MGLY                                          ', &
     '  MAOP + O3 --> 2 HCHO                                                                              ', &
     ' C2H6 + NO3 --> HNO3 + ETO2                                                                         ', &
     '  IALD + OH --> 0.44 IAO2 + 0.41 MAO3 + 0.15 HO2                                                    ', &
     '  IALD + O3 --> 0.2 ACO2 + 0.2 GLYX + 0.2 HAC + 0.12 HCHO + 0.6 MGLY ... etc.                       ', &
     '     2 MCO3 --> 2 MO2                                                                               ', &
     ' MO2 + MCO3 --> HCHO + MO2 + HO2                                                                    ', &
     ' MO2 + MCO3 --> ACTA + HCHO                                                                         ', &
     'R4O2 + MCO3 --> 0.32 ACET + 0.05 A3O2 + 0.18 B3O2 + 0.19 MEK + 0.32 ALD2 ... etc.                   ', &
     'ATO2 + MCO3 --> 0.2 HCHO + 0.8 MGLY + MO2 + 0.8 HO2 + 0.2 MCO3                                      ', &
     ' KO2 + MCO3 --> ALD2 + MO2 + MCO3                                                                   ', &
     'MCO3 + RIO2 --> 0.127 IALD + 0.69 HCHO + 0.136 RIO1 + 0.288 MACR + 0.402 MVK ... etc.               ', &
     'RIO1 + MCO3 --> IALD + 0.75 HCHO + MO2 + HO2                                                        ', &
     'IAO2 + MCO3 --> 0.29 CO + 0.18 GLYX + 0.36 HAC + 0.4 HCHO + 0.58 MGLY ... etc.                      ', &
     'MVN1 + MCO3 --> HAC + GLYC + NO2 + MO2                                                              ', &
     'MCO3 + VRO2 --> 0.28 HCHO + 0.28 MGLY + 0.72 GLYC + MO2 + 0.28 HO2 + 0.72 MCO3 ... etc.             ', &
     'MCO3 + MRO2 --> 0.83 CO + 0.83 HAC + 0.17 HCHO + 0.17 MGLY + MO2 + HO2 ... etc.                     ', &
     'B3O2 + MCO3 --> ACET + MO2 + HO2                                                                    ', &
     'R4N1 + MCO3 --> 0.3 R4O2 + 0.75 ALD2 + 0.39 HCHO + 0.57 RCHO + NO2 + MO2 ... etc.                   ', &
     'MVN2 + MCO3 --> HCHO + 0.5 MGLY + NO2 + MO2 + 0.5 HO2 + 0.5 MCO3                                    ', &
     'MAN2 + MCO3 --> HCHO + MGLY + NO2 + MO2                                                             ', &
     'INO2 + MCO3 --> 0.85 HNO3 + 0.15 HCHO + 0.1 MACR + 0.15 NO2 + 0.05 MVK ... etc.                     ', &
     'PRN1 + MCO3 --> ALD2 + HCHO + NO2 + MO2                                                             ', &
     'R4O2 + MCO3 --> ACTA + MEK                                                                          ', &
     'ATO2 + MCO3 --> ACTA + ROH                                                                          ', &
     ' KO2 + MCO3 --> ACTA + ROH                                                                          ', &
     'MCO3 + RIO2 --> ACTA + MEK                                                                          ', &
     'RIO1 + MCO3 --> ACTA + MEK                                                                          ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_7 = (/ &
     'IAO2 + MCO3 --> ACTA + MEK                                                                          ', &
     'MCO3 + VRO2 --> ACTA + MEK                                                                          ', &
     'MCO3 + MRO2 --> ACTA + MEK                                                                          ', &
     'R4N1 + MCO3 --> ACTA + RCHO + NO2                                                                   ', &
     'MVN1 + MCO3 --> ACTA + RCHO + NO2                                                                   ', &
     'MVN2 + MCO3 --> ACTA + RCHO + NO2                                                                   ', &
     'MAN2 + MCO3 --> ACTA + RCHO + NO2                                                                   ', &
     'INO2 + MCO3 --> ACTA + RCHO + NO2                                                                   ', &
     'PRN1 + MCO3 --> ACTA + RCHO + NO2                                                                   ', &
     'B3O2 + MCO3 --> ACET + ACTA                                                                         ', &
     'ETO2 + MCO3 --> ALD2 + MO2 + HO2                                                                    ', &
     'ETO2 + MCO3 --> ACTA + ALD2                                                                         ', &
     'RCO3 + MCO3 --> ETO2 + MO2                                                                          ', &
     'GCO3 + MCO3 --> HCHO + MO2 + HO2                                                                    ', &
     'MAO3 + MCO3 --> MO2 + HO2 + MCO3                                                                    ', &
     '      2 NO3 --> 2 NO2                                                                               ', &
     '    HO2 + x --> 0.5 H2O2 + x                                                                        ', &
     '    NO2 + x --> 0.5 HONO + 0.5 HNO3 + x                                                             ', &
     '    NO3 + x --> HNO3 + x                                                                            ', &
     '   N2O5 + x --> 2 HNO3 + x                                                                          ', &
     '         O3 --> 2 OH                                                                                ', &
     '        NO2 --> O3 + NO                                                                             ', &
     '       H2O2 --> 2 OH                                                                                ', &
     '         MP --> HCHO + HO2 + OH                                                                     ', &
     '       HCHO --> CO + 2 HO2                                                                          ', &
     '       HCHO --> CO                                                                                  ', &
     '       HNO3 --> NO2 + OH                                                                            ', &
     '       HONO --> OH + NO                                                                             ', &
     '       HNO4 --> 0.667 NO2 + 0.333 NO3 + 0.667 HO2 + 0.333 OH                                        ', &
     '        NO3 --> NO2 + O3                                                                            ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_8 = (/ &
     '        NO3 --> NO                                                                                  ', &
     '       N2O5 --> NO2 + NO3                                                                           ', &
     '       ALD2 --> CO + MO2 + HO2                                                                      ', &
     '        PAN --> NO2 + MCO3                                                                          ', &
     '       RCHO --> CO + ETO2 + HO2                                                                     ', &
     '       ACET --> MO2 + MCO3                                                                          ', &
     '        MEK --> ETO2 + MCO3                                                                         ', &
     '       GLYC --> CO + HCHO + 2 HO2                                                                   ', &
     '       GLYX --> 1.667 CO + 0.333 HCHO + 0.67 HO2                                                    ', &
     '       MGLY --> CO + 0.5 ALD2 + 0.5 HO2 + 0.5 MCO3                                                  ', &
     '        MVK --> PRPE + CO                                                                           ', &
     '        MVK --> CO + HCHO + HO2 + MCO3                                                              ', &
     '        MVK --> MAO3 + MO2                                                                          ', &
     '       MACR --> MAO3 + HO2                                                                          ', &
     '       MACR --> CO + 0.2 HCHO + 0.8 MGLY + 1.8 HO2 + 0.2 MCO3                                       ', &
     '        HAC --> HCHO + HO2 + MCO3                                                                   ', &
     '       INPN --> RCHO + NO2 + HO2 + OH                                                               ', &
     '       PRPN --> RCHO + NO2 + HO2 + OH                                                               ', &
     '        ETP --> ALD2 + HO2 + OH                                                                     ', &
     '       RA3P --> RCHO + HO2 + OH                                                                     ', &
     '       RB3P --> RCHO + HO2 + OH                                                                     ', &
     '        R4P --> RCHO + HO2 + OH                                                                     ', &
     '         PP --> RCHO + HO2 + OH                                                                     ', &
     '         RP --> ALD2 + HO2 + OH                                                                     ', &
     '         GP --> HCHO + HO2 + OH                                                                     ', &
     '        RIP --> 0.127 IALD + 0.69 HCHO + 0.136 RIO1 + 0.288 MACR + 0.402 MVK ... etc.               ', &
     '        IAP --> 0.67 CO + 0.36 HAC + 0.58 MGLY + 0.26 GLYC + HO2 + OH ... etc.                      ', &
     '       MVNP --> RCHO + NO2 + HO2 + OH                                                               ', &
     '        VRP --> 0.28 HCHO + 0.28 MGLY + 0.72 GLYC + 0.28 HO2 + 0.72 MCO3 ... etc.                   ', &
     '        MRP --> 0.83 CO + 0.83 HAC + 0.17 HCHO + 0.17 MGLY + HO2 + OH ... etc.                      ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_9 = (/ &
     '       MAOP --> RCHO + HO2 + OH                                                                     ', &
     '       R4N2 --> 0.32 ACET + 0.05 A3O2 + 0.18 B3O2 + 0.19 MEK + 0.32 ALD2 ... etc.                   ', &
     '        MAP --> MO2 + OH                                                                            ', &
     '  RCOH + OH --> CO2 + ETO2                                                                          ', &
     '   PAN + OH --> HCHO + NO2                                                                          ', &
     '   PPN + OH --> ALD2 + NO2                                                                          ', &
     '  H2O + NO2 --> HONO + HNO3                                                                         ', &
     ' HCHO + HO2 --> AHO2                                                                                ', &
     '  AHO2 + NO --> ACO2 + NO2 + HO2                                                                    ', &
     ' AHO2 + HO2 --> ACO2                                                                                ', &
     '     2 AHO2 --> 2 ACO2 + 2 HO2                                                                      ', &
     '   AHO2 + x --> HCHO + HO2 + x                                                                      ', &
     '  ISNT + OH --> ISNR                                                                                ', &
     '  ISNR + NO --> 0.05 ISNT + 0.95 HAC + 0.95 GLYC + 1.95 NO2 + 0.05 HO2 ... etc.                     ', &
     ' ISNR + HO2 --> ISNP                                                                                ', &
     '  ISNP + OH --> ISNR                                                                                ', &
     '  ISNR + O3 --> 0.11 CHO2 + 0.04 ALD2 + 0.8 HCHO + 0.82 MGLY + NO2 + 0.06 HO2 ... etc.              ', &
     '  ALK7 + OH --> R7O2                                                                                ', &
     '  R7O2 + NO --> 0.75 R7O1 + 0.25 R4O2 + 0.25 MEK + NO2                                              ', &
     '  R7O2 + NO --> R7N2                                                                                ', &
     '  R7O1 + NO --> RCHO + NO2 + HO2                                                                    ', &
     '  R7O1 + NO --> R7N2                                                                                ', &
     ' ALK7 + NO3 --> HNO3 + R7O2                                                                         ', &
     '  R7N2 + OH --> R7N1                                                                                ', &
     '  R7N1 + NO --> 0.11 R6N1 + 0.65 R5N1 + 0.65 ALD2 + 0.11 HCHO + 0.48 RCHO ... etc.                  ', &
     '  R6N1 + NO --> R5N1 + HCHO + NO2                                                                   ', &
     '  R5N1 + NO --> HCHO + RCHO + 2 NO2                                                                 ', &
     '     2 A3O2 --> 0.4 EOH + 0.4 ALD2 + 1.2 RCHO + 1.2 HO2                                             ', &
     ' R7O2 + HO2 --> R7P                                                                                 ', &
     ' R7N1 + HO2 --> R7N2                                                                                ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_10 = (/ &
     ' R6N1 + HO2 --> R7N2                                                                                ', &
     ' R5N1 + HO2 --> R4N2                                                                                ', &
     '  A3N2 + OH --> R3N1                                                                                ', &
     '  R3N1 + NO --> ALD2 + HCHO + 2 NO2                                                                 ', &
     '  ETHE + OH --> EO2                                                                                 ', &
     '   EO2 + NO --> 0.2 HAC + 1.6 HCHO + NO2 + HO2                                                      ', &
     '  ETHE + O3 --> 0.06 CH4 + 0.42 CO + 0.4 CHO2 + HCHO + 0.2 HO2 + 0.2 OH ... etc.                    ', &
     '  BUTE + OH --> BUO2                                                                                ', &
     '  BUO2 + NO --> 1.8 ALD2 + 0.1 R4N2 + 0.9 NO2 + 0.9 HO2                                             ', &
     '  BUTE + O3 --> 0.4 CRO2 + ALD2 + 0.35 MO2 + 0.25 HO2 + 0.6 OH                                      ', &
     '  CHO2 + NO --> HCHO + NO2                                                                          ', &
     ' CHO2 + NO2 --> HCHO + NO3                                                                          ', &
     ' H2O + CHO2 --> ACO2                                                                                ', &
     '  CRO2 + NO --> ALD2 + NO2                                                                          ', &
     ' CRO2 + NO2 --> ALD2 + NO3                                                                          ', &
     ' H2O + CRO2 --> ACO2                                                                                ', &
     '  EO2 + HO2 --> EP                                                                                  ', &
     ' BUO2 + HO2 --> BUP                                                                                 ', &
     ' SO2 + CHO2 --> SULF + HCHO                                                                         ', &
     ' SO2 + CRO2 --> SULF + ALD2                                                                         ', &
     ' BUTE + NO3 --> PRN1                                                                                ', &
     '  BENZ + OH --> 0.75 ADDB + 0.25 PHEN + 0.25 HO2                                                    ', &
     '  ADDB + NO --> DIAL + GLYX + NO2 + HO2                                                             ', &
     '  TOLU + OH --> 0.16 CRES + 0.08 ARO2 + 0.76 ADDT + 0.16 HO2                                        ', &
     '  ARO2 + NO --> 0.9 ACHO + 0.1 R4N2 + 0.9 NO2 + 0.9 HO2                                             ', &
     '  ADDT + NO --> 0.8 DIAL + 0.15 ADAL + 0.05 MDAL + 0.2 GLYX + 0.8 MGLY ... etc.                     ', &
     '  XYLE + OH --> 0.17 DMP + 0.83 ADDX + 0.17 HO2                                                     ', &
     '  ADDX + NO --> 0.5 ADAL + 0.5 MDAL + MGLY + NO2 + HO2                                              ', &
     '  PHEN + OH --> 0.9 ADD2 + 0.1 POXY                                                                 ', &
     '  CRES + OH --> 0.9 ADD2 + 0.1 POXY                                                                 ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_11 = (/ &
     '   DMP + OH --> 0.9 ADD2 + 0.1 POXY                                                                 ', &
     ' POXY + NO2 --> NITP                                                                                ', &
     ' POXY + HO2 --> PHEN                                                                                ', &
     '  ADD2 + NO --> ADI + NO2 + HO2                                                                     ', &
     '   ADI + OH --> AO2                                                                                 ', &
     '  AO2 + NO2 --> APAN                                                                                ', &
     '   APAN + x --> AO2 + NO2 + x                                                                       ', &
     '   AO2 + NO --> AO1 + NO2                                                                           ', &
     '   AO1 + NO --> AO0 + NO2                                                                           ', &
     '   AO0 + NO --> CO + GLYX + NO2 + HO2                                                               ', &
     ' PHEN + NO3 --> POXY + HNO3                                                                         ', &
     ' CRES + NO3 --> POXY + HNO3                                                                         ', &
     '  DMP + NO3 --> POXY + HNO3                                                                         ', &
     ' NITP + NO3 --> HNO3 + R4N2                                                                         ', &
     '  DIAL + OH --> DCO3                                                                                ', &
     '  MDAL + OH --> XCO3                                                                                ', &
     '  ADAL + OH --> 0.5 ZCO3 + 0.5 YCO3                                                                 ', &
     ' DCO3 + NO2 --> DPAN                                                                                ', &
     ' XCO3 + NO2 --> XPAN                                                                                ', &
     ' YCO3 + NO2 --> YPAN                                                                                ', &
     ' ZCO3 + NO2 --> ZPAN                                                                                ', &
     '   DPAN + x --> DCO3 + NO2 + x                                                                      ', &
     '   XPAN + x --> XCO3 + NO2 + x                                                                      ', &
     '   YPAN + x --> YCO3 + NO2 + x                                                                      ', &
     '   ZPAN + x --> ZCO3 + NO2 + x                                                                      ', &
     '  DCO3 + NO --> DCO2 + NO2                                                                          ', &
     '  DCO2 + NO --> DCO1 + NO2                                                                          ', &
     '  DCO1 + NO --> CO + GLYX + NO2 + HO2                                                               ', &
     '  XCO3 + NO --> XCO2 + NO2                                                                          ', &
     '  XCO2 + NO --> XCO1 + NO2                                                                          ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_12 = (/ &
     '  XCO1 + NO --> CO + 0.5 GLYX + 0.5 MGLY + NO2 + 0.5 HO2 + 0.5 MCO3 ... etc.                        ', &
     '  YCO3 + NO --> YCO2 + NO2                                                                          ', &
     '  YCO2 + NO --> YCO1 + NO2                                                                          ', &
     '  YCO1 + NO --> CO + 0.5 GLYX + 0.5 MGLY + NO2 + 0.5 HO2 + 0.5 MCO3 ... etc.                        ', &
     '  ZCO3 + NO --> ZCO2 + NO2                                                                          ', &
     '  ZCO2 + NO --> ZCO1 + NO2                                                                          ', &
     '  ZCO1 + NO --> CO + MGLY + NO2 + HO2                                                               ', &
     '       DIAL --> DCO3 + HO2                                                                          ', &
     '       MDAL --> 0.5 DCO3 + 0.5 XCO3 + 0.5 HO2 + 0.5 MCO3                                            ', &
     '       ADAL --> 0.5 ZCO3 + 0.5 YCO3 + HO2                                                           ', &
     '  ACHO + OH --> BCO3                                                                                ', &
     ' BCO3 + NO2 --> PBZN                                                                                ', &
     '   PBZN + x --> BCO3 + NO2 + x                                                                      ', &
     '  BCO3 + NO --> PHO2 + NO2                                                                          ', &
     '  PHO2 + NO --> POXY + NO2                                                                          ', &
     ' ADDB + HO2 --> ADBP                                                                                ', &
     ' ARO2 + HO2 --> ARP                                                                                 ', &
     ' ADDT + HO2 --> ADTP                                                                                ', &
     ' ADDX + HO2 --> ADXP                                                                                ', &
     ' ADD2 + HO2 --> AD2P                                                                                ', &
     '  AO2 + HO2 --> 0.75 AP + 0.25 EOH + 0.25 O3                                                        ', &
     '  AO1 + HO2 --> 0.75 AP + 0.25 EOH + 0.25 O3                                                        ', &
     '  AO0 + HO2 --> 0.75 AP + 0.25 EOH + 0.25 O3                                                        ', &
     ' DCO3 + HO2 --> 0.75 DAP + 0.25 EOH + 0.25 O3                                                       ', &
     ' DCO2 + HO2 --> 0.75 DAP + 0.25 EOH + 0.25 O3                                                       ', &
     ' DCO1 + HO2 --> 0.75 DAP + 0.25 EOH + 0.25 O3                                                       ', &
     ' XCO3 + HO2 --> 0.75 XAP + 0.25 EOH + 0.25 O3                                                       ', &
     ' XCO2 + HO2 --> 0.75 XAP + 0.25 EOH + 0.25 O3                                                       ', &
     ' XCO1 + HO2 --> 0.75 XAP + 0.25 EOH + 0.25 O3                                                       ', &
     ' YCO3 + HO2 --> 0.75 YAP + 0.25 EOH + 0.25 O3                                                       ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_13 = (/ &
     ' YCO2 + HO2 --> 0.75 YAP + 0.25 EOH + 0.25 O3                                                       ', &
     ' YCO1 + HO2 --> 0.75 YAP + 0.25 EOH + 0.25 O3                                                       ', &
     ' ZCO3 + HO2 --> 0.75 ZAP + 0.25 EOH + 0.25 O3                                                       ', &
     ' ZCO2 + HO2 --> 0.75 ZAP + 0.25 EOH + 0.25 O3                                                       ', &
     ' ZCO1 + HO2 --> 0.75 ZAP + 0.25 EOH + 0.25 O3                                                       ', &
     ' BCO3 + HO2 --> 0.75 BAP + 0.25 EOH + 0.25 O3                                                       ', &
     ' PHO2 + HO2 --> 0.75 PHP + 0.25 EOH + 0.25 O3                                                       ', &
     '  APIN + OH --> PIO2                                                                                ', &
     '  PIO2 + NO --> 0.2 PINT + 0.8 MEK + 0.8 ALD2 + 0.8 NO2 + 0.8 HO2                                   ', &
     ' PIO2 + HO2 --> PIP                                                                                 ', &
     '  APIN + O3 --> 0.02 H2O2 + 0.14 CO + 0.2 EO2 + 0.53 MEK + 0.065 ALD2 ... etc.                      ', &
     ' APIN + NO3 --> 0.9 PIN2 + 0.1 INO2                                                                 ', &
     '  PIN2 + NO --> 0.464 MEK + 1.24 ALD2 + 0.287 HCHO + 2 NO2                                          ', &
     ' PIN2 + NO2 --> 2 ISNP                                                                              ', &
     ' PIN2 + HO2 --> ISNP                                                                                ', &
     '  LIMO + OH --> LIO2                                                                                ', &
     '  LIO2 + NO --> 0.35 PINT + 0.4 IPRD + 0.25 BUTE + 0.25 HCHO + 0.65 NO2 ... etc.                    ', &
     '  PINT + OH --> ISNR                                                                                ', &
     ' LIO2 + HO2 --> LIP                                                                                 ', &
     '  LIMO + O3 --> 0.02 H2O2 + 0.08 ACO2 + 0.46 PRPE + 0.14 CO + 0.16 EO2 ... etc.                     ', &
     ' LIMO + NO3 --> 0.87 PIN2 + 0.13 INO2                                                               ', &
     '  IPRD + OH --> IPO2                                                                                ', &
     '  IPO2 + NO --> 0.418 CO + 0.124 GLYX + 0.48 HAC + 0.145 MGLY + 0.125 GLYC ... etc.                 ', &
     ' HO2 + IPO2 --> MRP                                                                                 ', &
     '    EP + OH --> 0.5 EO2 + 0.5 HAC + 0.5 OH                                                          ', &
     '   R7P + OH --> 0.5 R7O2 + 0.5 RCHO + 0.5 OH                                                        ', &
     '  ADBP + OH --> ADDB                                                                                ', &
     '   ARP + OH --> ARO2                                                                                ', &
     '  ADTP + OH --> ADDT                                                                                ', &
     '  ADXP + OH --> ADDX                                                                                ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_14 = (/ &
     '  AD2P + OH --> ADD2                                                                                ', &
     '   BAP + OH --> BCO3                                                                                ', &
     '   PHP + OH --> PHO2                                                                                ', &
     '    AP + OH --> 0.5 AO2 + 0.5 RCHO + 0.5 OH                                                         ', &
     '   DAP + OH --> 0.5 DCO3 + 0.5 RCHO + 0.5 OH                                                        ', &
     '   XAP + OH --> 0.5 XCO3 + 0.5 RCHO + 0.5 OH                                                        ', &
     '   YAP + OH --> 0.5 YCO3 + 0.5 RCHO + 0.5 OH                                                        ', &
     '   ZAP + OH --> 0.5 ZCO3 + 0.5 RCHO + 0.5 OH                                                        ', &
     '       ADTP --> RCHO + HO2 + OH                                                                     ', &
     '       ADXP --> RCHO + HO2 + OH                                                                     ', &
     '       AD2P --> RCHO + HO2 + OH                                                                     ', &
     '        BAP --> RCHO + HO2 + OH                                                                     ', &
     '        PHP --> RCHO + HO2 + OH                                                                     ', &
     '   BUP + OH --> 0.5 BUO2 + 0.5 RCHO + HO2                                                           ', &
     '        BUP --> RCHO + HO2 + OH                                                                     ', &
     '        R7P --> RCHO + HO2 + OH                                                                     ', &
     '         EP --> HAC + HO2 + OH                                                                      ', &
     '   PIP + OH --> 0.5 PIO2 + 0.5 MEK + 0.5 ALD2 + HO2                                                 ', &
     '   PIP + O3 --> 0.7 HCHO                                                                            ', &
     '   LIP + OH --> 0.3 IPRD + 0.5 LIO2 + 0.19 BUTE + 0.19 HCHO + HO2                                   ', &
     '   LIP + O3 --> 0.7 HCHO                                                                            ', &
     '        PIP --> HAC + HO2 + OH                                                                      ', &
     '        LIP --> HAC + HO2 + OH                                                                      ', &
     '  APAN + OH --> GLYX + NO2                                                                          ', &
     '  DPAN + OH --> GLYX + NO2                                                                          ', &
     '  XPAN + OH --> 0.5 GLYX + 0.5 MGLY + NO2                                                           ', &
     '  YPAN + OH --> MGLY + NO2                                                                          ', &
     '  ZPAN + OH --> MGLY + NO2                                                                          ', &
     '  PBZN + OH --> POXY + NO2                                                                          ', &
     '  IPAN + OH --> HCHO + NO2                                                                          ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_15 = (/ &
     '     2 RCO3 --> 2 ETO2                                                                              ', &
     '      2 AO2 --> 2 AO0                                                                               ', &
     '  AO2 + MO2 --> 0.85 AO0 + 0.15 EOH + MO2                                                           ', &
     '  AO2 + MO2 --> AO2 + HCHO + 0.5 HO2                                                                ', &
     ' AO2 + MCO3 --> AO0 + MCO3                                                                          ', &
     ' AO2 + MCO3 --> AO2 + MO2                                                                           ', &
     '     2 DCO3 --> 2 DCO1                                                                              ', &
     ' DCO3 + MO2 --> 0.85 DCO1 + 0.15 EOH + MO2                                                          ', &
     ' DCO3 + MO2 --> DCO3 + HCHO + 0.5 HO2                                                               ', &
     'DCO3 + MCO3 --> DCO1 + MCO3                                                                         ', &
     'DCO3 + MCO3 --> DCO3 + MO2                                                                          ', &
     '     2 XCO3 --> 2 XCO1                                                                              ', &
     ' XCO3 + MO2 --> 0.85 XCO1 + 0.15 EOH + MO2                                                          ', &
     ' XCO3 + MO2 --> XCO3 + HCHO + 0.5 HO2                                                               ', &
     'XCO3 + MCO3 --> XCO1 + MCO3                                                                         ', &
     'XCO3 + MCO3 --> XCO3 + MO2                                                                          ', &
     '     2 YCO3 --> 2 YCO1                                                                              ', &
     ' YCO3 + MO2 --> 0.85 YCO1 + 0.15 EOH + MO2                                                          ', &
     ' YCO3 + MO2 --> YCO3 + HCHO + 0.5 HO2                                                               ', &
     'YCO3 + MCO3 --> YCO1 + MCO3                                                                         ', &
     'YCO3 + MCO3 --> YCO3 + MO2                                                                          ', &
     '     2 ZCO3 --> 2 ZCO1                                                                              ', &
     ' ZCO3 + MO2 --> 0.85 ZCO1 + 0.15 EOH + MO2                                                          ', &
     ' ZCO3 + MO2 --> ZCO3 + HCHO + 0.5 HO2                                                               ', &
     'ZCO3 + MCO3 --> ZCO1 + MCO3                                                                         ', &
     'ZCO3 + MCO3 --> ZCO3 + MO2                                                                          ', &
     '     2 BCO3 --> 2 PHO2                                                                              ', &
     ' BCO3 + MO2 --> 0.85 PHO2 + 0.15 EOH + MO2                                                          ', &
     ' BCO3 + MO2 --> BCO3 + HCHO + 0.5 HO2                                                               ', &
     'BCO3 + MCO3 --> PHO2 + MCO3                                                                         ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_16 = (/ &
     'BCO3 + MCO3 --> BCO3 + MO2                                                                          ', &
     '     2 MAO3 --> 2 MAO2                                                                              ', &
     ' MAO3 + MO2 --> 0.85 MAO2 + 0.15 EOH + MO2                                                          ', &
     ' MAO3 + MO2 --> HCHO + MAO3 + 0.5 HO2                                                               ', &
     '     2 HACO --> 2 MO2                                                                               ', &
     ' HACO + MO2 --> 0.15 EOH + 1.85 MO2                                                                 ', &
     ' HACO + MO2 --> HACO + HCHO + 0.5 HO2                                                               ', &
     'HACO + MCO3 --> MO2 + MCO3                                                                          ', &
     'HACO + MCO3 --> HACO + MO2                                                                          ', &
     ' R7O2 + MO2 --> R7O2 + HCHO + HO2                                                                   ', &
     ' R7O2 + MO2 --> 0.14 ACET + 0.28 MEK + 0.07 ALD2 + 0.35 RCHO + MO2                                  ', &
     '  EO2 + MO2 --> EO2 + HCHO + HO2                                                                    ', &
     '  EO2 + MO2 --> 0.45 ALD2 + 0.55 HCHO + MO2                                                         ', &
     ' BUO2 + MO2 --> BUO2 + HCHO + HO2                                                                   ', &
     ' BUO2 + MO2 --> 0.19 MEK + 0.93 ALD2 + MO2                                                          ', &
     ' ADDT + MO2 --> ADDT + HCHO + HO2                                                                   ', &
     ' ADDT + MO2 --> 0.56 DIAL + 0.105 ADAL + 0.035 MDAL + 0.16 GLYX + 0.17 MGLY ... etc.                ', &
     ' ADDX + MO2 --> ADDX + HCHO + HO2                                                                   ', &
     ' ADDX + MO2 --> 0.406 ADAL + 0.4 MDAL + 0.45 MGLY + MO2 + HO2                                       ', &
     ' PIO2 + MO2 --> MEK + ALD2 + MO2 + HO2                                                              ', &
     ' PIO2 + MO2 --> PIO2 + HCHO + HO2                                                                   ', &
     ' LIO2 + MO2 --> 0.6 IPRD + 0.38 BUTE + 0.38 HCHO + MO2 + HO2                                        ', &
     ' LIO2 + MO2 --> LIO2 + HCHO + HO2                                                                   ', &
     'R7O2 + MCO3 --> 0.5 ACO2 + R7O2 + 0.5 MO2 + 0.5 HO2                                                 ', &
     'R7O2 + MCO3 --> 0.19 ACET + 0.39 MEK + 0.1 ALD2 + 0.4 RCHO + MCO3                                   ', &
     ' EO2 + MCO3 --> 0.5 ACO2 + EO2 + 0.5 MO2 + 0.5 HO2                                                  ', &
     ' EO2 + MCO3 --> 0.6 ALD2 + 0.8 HCHO + MCO3                                                          ', &
     'BUO2 + MCO3 --> 0.5 ACO2 + BUO2 + 0.5 MO2 + 0.5 HO2                                                 ', &
     'BUO2 + MCO3 --> 0.569 MEK + 0.941 ALD2 + MCO3                                                       ', &
     'ADDT + MCO3 --> ADDT + MO2 + HO2                                                                    ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(24) :: EQN_NAMES_17 = (/ &
     'ADDT + MCO3 --> 0.8 DIAL + 0.15 ADAL + 0.05 MDAL + 0.65 GLYX + 0.35 MGLY ... etc.                   ', &
     'ADDX + MCO3 --> ADDX + MO2 + HO2                                                                    ', &
     'ADDX + MCO3 --> 0.5 ADAL + 0.5 MDAL + 0.37 GLYX + 0.63 MGLY + MCO3                                  ', &
     'PIO2 + MCO3 --> PIO2 + MO2 + HO2                                                                    ', &
     'PIO2 + MCO3 --> MEK + ALD2 + MCO3                                                                   ', &
     'LIO2 + MCO3 --> LIO2 + MO2 + HO2                                                                    ', &
     'LIO2 + MCO3 --> 0.6 IPRD + 0.4 BUTE + 0.4 HCHO + MCO3                                               ', &
     '     2 RIO2 --> 0.93 IPRD + 1.07 HCHO + 0.39 MACR + 0.68 MVK + 1.38 HO2 ... etc.                    ', &
     'RIO2 + IPO2 --> 0.465 IPRD + 0.48 CO + 0.124 GLYX + 0.48 HAC + 0.535 HCHO ... etc.                  ', &
     'RIO2 + VRO2 --> 0.465 IPRD + 1.235 HCHO + MGLY + 0.195 MACR + 0.34 MVK ... etc.                     ', &
     'RIO2 + MRO2 --> 0.465 IPRD + 1.235 HCHO + MGLY + 0.195 MACR + 0.34 MVK ... etc.                     ', &
     '     2 IPO2 --> 0.82 CO + 0.248 GLYX + 0.96 HAC + 0.29 MGLY + 0.25 GLYC ... etc.                    ', &
     'IPO2 + VRO2 --> 0.48 CO + 0.124 GLYX + 0.48 HAC + 0.7 HCHO + 1.145 MGLY ... etc.                    ', &
     'IPO2 + MRO2 --> 0.48 CO + 0.124 GLYX + 0.48 HAC + 0.7 HCHO + 1.145 MGLY ... etc.                    ', &
     '     2 VRO2 --> 1.4 HCHO + 2 MGLY + 1.4 HO2                                                         ', &
     'VRO2 + MRO2 --> 1.4 HCHO + 2 MGLY + 1.4 HO2                                                         ', &
     '     2 MRO2 --> 1.4 HCHO + 2 MGLY + 1.4 HO2                                                         ', &
     '      2 EO2 --> 0.4 EOH + 0.4 ALD2 + 1.2 HAC + 1.2 HO2                                              ', &
     '      2 PO2 --> 0.4 EOH + 0.4 ALD2 + 1.2 RCHO + 1.2 HO2                                             ', &
     '      2 KO2 --> 0.44 ACET + 2 ALD2                                                                  ', &
     '   DMS + OH --> SO2 + HCHO + MO2                                                                    ', &
     '   DMS + OH --> 0.75 SO2 + CO + MO2                                                                 ', &
     '  DMS + NO3 --> SO2 + HNO3 + HCHO + MO2                                                             ', &
     '   SO2 + OH --> SULF + HO2                                                                          ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(534) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3, EQN_NAMES_4, &
    EQN_NAMES_5, EQN_NAMES_6, EQN_NAMES_7, EQN_NAMES_8, EQN_NAMES_9, &
    EQN_NAMES_10, EQN_NAMES_11, EQN_NAMES_12, EQN_NAMES_13, EQN_NAMES_14, &
    EQN_NAMES_15, EQN_NAMES_16, EQN_NAMES_17 /)

! INLINED global variables

! End INLINED global variables


END MODULE gasphs_Monitor
