! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gasphs_Parameters.f90
! Time                 : Tue Mar 10 15:03:35 2009
! Working directory    : /scratch/ASHALABY/KPP/COMPARE/SILLMAN
! Equation file        : gasphs.kpp
! Output root filename : gasphs
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gasphs_Parameters

  USE gasphs_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 176 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 175 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 172 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 1 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 534 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 176 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 1983 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 2336 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 176 
! CNEQN - (NREACT+1) Number stoicm elements in compressed col format
  INTEGER, PARAMETER :: CNEQN = 535 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 3 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 2 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 
! MODEL DIMENSIONS
!  INTEGER,PARAMETER :: IX=50,JX=80,KX=18

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_SULF = 1 
  INTEGER, PARAMETER :: ind_MAO2 = 2 
  INTEGER, PARAMETER :: ind_CO2 = 3 
  INTEGER, PARAMETER :: ind_H2 = 4 
  INTEGER, PARAMETER :: ind_C3H8 = 5 
  INTEGER, PARAMETER :: ind_IPAN = 6 
  INTEGER, PARAMETER :: ind_BENZ = 7 
  INTEGER, PARAMETER :: ind_XYLE = 8 
  INTEGER, PARAMETER :: ind_GPAN = 9 
  INTEGER, PARAMETER :: ind_TOLU = 10 
  INTEGER, PARAMETER :: ind_CH4 = 11 
  INTEGER, PARAMETER :: ind_N2O5 = 12 
  INTEGER, PARAMETER :: ind_ADI = 13 
  INTEGER, PARAMETER :: ind_ACHO = 14 
  INTEGER, PARAMETER :: ind_ADBP = 15 
  INTEGER, PARAMETER :: ind_ARP = 16 
  INTEGER, PARAMETER :: ind_C2H6 = 17 
  INTEGER, PARAMETER :: ind_ALK4 = 18 
  INTEGER, PARAMETER :: ind_ALK7 = 19 
  INTEGER, PARAMETER :: ind_A3N2 = 20 
  INTEGER, PARAMETER :: ind_PINT = 21 
  INTEGER, PARAMETER :: ind_NITP = 22 
  INTEGER, PARAMETER :: ind_R7O1 = 23 
  INTEGER, PARAMETER :: ind_HACO = 24 
  INTEGER, PARAMETER :: ind_CRES = 25 
  INTEGER, PARAMETER :: ind_DMP = 26 
  INTEGER, PARAMETER :: ind_H2O2 = 27 
  INTEGER, PARAMETER :: ind_ISNP = 28 
  INTEGER, PARAMETER :: ind_HONO = 29 
  INTEGER, PARAMETER :: ind_HNO4 = 30 
  INTEGER, PARAMETER :: ind_PAN = 31 
  INTEGER, PARAMETER :: ind_R7N2 = 32 
  INTEGER, PARAMETER :: ind_PPN = 33 
  INTEGER, PARAMETER :: ind_APAN = 34 
  INTEGER, PARAMETER :: ind_DPAN = 35 
  INTEGER, PARAMETER :: ind_YPAN = 36 
  INTEGER, PARAMETER :: ind_ZPAN = 37 
  INTEGER, PARAMETER :: ind_PBZN = 38 
  INTEGER, PARAMETER :: ind_RCOH = 39 
  INTEGER, PARAMETER :: ind_MP = 40 
  INTEGER, PARAMETER :: ind_ETP = 41 
  INTEGER, PARAMETER :: ind_RA3P = 42 
  INTEGER, PARAMETER :: ind_RB3P = 43 
  INTEGER, PARAMETER :: ind_R4P = 44 
  INTEGER, PARAMETER :: ind_R7P = 45 
  INTEGER, PARAMETER :: ind_MAP = 46 
  INTEGER, PARAMETER :: ind_EP = 47 
  INTEGER, PARAMETER :: ind_PP = 48 
  INTEGER, PARAMETER :: ind_RP = 49 
  INTEGER, PARAMETER :: ind_GP = 50 
  INTEGER, PARAMETER :: ind_ADTP = 51 
  INTEGER, PARAMETER :: ind_ADXP = 52 
  INTEGER, PARAMETER :: ind_AD2P = 53 
  INTEGER, PARAMETER :: ind_BAP = 54 
  INTEGER, PARAMETER :: ind_PHP = 55 
  INTEGER, PARAMETER :: ind_BUP = 56 
  INTEGER, PARAMETER :: ind_DMS = 57 
  INTEGER, PARAMETER :: ind_XPAN = 58 
  INTEGER, PARAMETER :: ind_AHO2 = 59 
  INTEGER, PARAMETER :: ind_AP = 60 
  INTEGER, PARAMETER :: ind_DAP = 61 
  INTEGER, PARAMETER :: ind_XAP = 62 
  INTEGER, PARAMETER :: ind_YAP = 63 
  INTEGER, PARAMETER :: ind_ZAP = 64 
  INTEGER, PARAMETER :: ind_R3N1 = 65 
  INTEGER, PARAMETER :: ind_ETHE = 66 
  INTEGER, PARAMETER :: ind_ISNT = 67 
  INTEGER, PARAMETER :: ind_DIAL = 68 
  INTEGER, PARAMETER :: ind_ADDB = 69 
  INTEGER, PARAMETER :: ind_ARO2 = 70 
  INTEGER, PARAMETER :: ind_PHEN = 71 
  INTEGER, PARAMETER :: ind_IPRD = 72 
  INTEGER, PARAMETER :: ind_R6N1 = 73 
  INTEGER, PARAMETER :: ind_R5N1 = 74 
  INTEGER, PARAMETER :: ind_H2O = 75 
  INTEGER, PARAMETER :: ind_SO2 = 76 
  INTEGER, PARAMETER :: ind_ADAL = 77 
  INTEGER, PARAMETER :: ind_MAOP = 78 
  INTEGER, PARAMETER :: ind_YCO2 = 79 
  INTEGER, PARAMETER :: ind_AO1 = 80 
  INTEGER, PARAMETER :: ind_DCO2 = 81 
  INTEGER, PARAMETER :: ind_ZCO2 = 82 
  INTEGER, PARAMETER :: ind_XCO2 = 83 
  INTEGER, PARAMETER :: ind_MPAN = 84 
  INTEGER, PARAMETER :: ind_ACO2 = 85 
  INTEGER, PARAMETER :: ind_MDAL = 86 
  INTEGER, PARAMETER :: ind_ADD2 = 87 
  INTEGER, PARAMETER :: ind_PRPN = 88 
  INTEGER, PARAMETER :: ind_R7N1 = 89 
  INTEGER, PARAMETER :: ind_VRP = 90 
  INTEGER, PARAMETER :: ind_IAP = 91 
  INTEGER, PARAMETER :: ind_PIP = 92 
  INTEGER, PARAMETER :: ind_LIP = 93 
  INTEGER, PARAMETER :: ind_ACET = 94 
  INTEGER, PARAMETER :: ind_APIN = 95 
  INTEGER, PARAMETER :: ind_INPN = 96 
  INTEGER, PARAMETER :: ind_LIMO = 97 
  INTEGER, PARAMETER :: ind_PRPE = 98 
  INTEGER, PARAMETER :: ind_MRP = 99 
  INTEGER, PARAMETER :: ind_ISOP = 100 
  INTEGER, PARAMETER :: ind_MVNP = 101 
  INTEGER, PARAMETER :: ind_ACTA = 102 
  INTEGER, PARAMETER :: ind_PHO2 = 103 
  INTEGER, PARAMETER :: ind_PIN2 = 104 
  INTEGER, PARAMETER :: ind_CO = 105 
  INTEGER, PARAMETER :: ind_AO0 = 106 
  INTEGER, PARAMETER :: ind_DCO1 = 107 
  INTEGER, PARAMETER :: ind_ZCO1 = 108 
  INTEGER, PARAMETER :: ind_RIP = 109 
  INTEGER, PARAMETER :: ind_YCO1 = 110 
  INTEGER, PARAMETER :: ind_XCO1 = 111 
  INTEGER, PARAMETER :: ind_EOH = 112 
  INTEGER, PARAMETER :: ind_ROH = 113 
  INTEGER, PARAMETER :: ind_CHO2 = 114 
  INTEGER, PARAMETER :: ind_CRO2 = 115 
  INTEGER, PARAMETER :: ind_EO2 = 116 
  INTEGER, PARAMETER :: ind_GCO3 = 117 
  INTEGER, PARAMETER :: ind_MOH = 118 
  INTEGER, PARAMETER :: ind_A3O2 = 119 
  INTEGER, PARAMETER :: ind_B3O2 = 120 
  INTEGER, PARAMETER :: ind_R4N1 = 121 
  INTEGER, PARAMETER :: ind_BUO2 = 122 
  INTEGER, PARAMETER :: ind_BCO3 = 123 
  INTEGER, PARAMETER :: ind_POXY = 124 
  INTEGER, PARAMETER :: ind_HNO3 = 125 
  INTEGER, PARAMETER :: ind_MAN2 = 126 
  INTEGER, PARAMETER :: ind_ADDT = 127 
  INTEGER, PARAMETER :: ind_ADDX = 128 
  INTEGER, PARAMETER :: ind_ZCO3 = 129 
  INTEGER, PARAMETER :: ind_DCO3 = 130 
  INTEGER, PARAMETER :: ind_XCO3 = 131 
  INTEGER, PARAMETER :: ind_YCO3 = 132 
  INTEGER, PARAMETER :: ind_AO2 = 133 
  INTEGER, PARAMETER :: ind_GLYX = 134 
  INTEGER, PARAMETER :: ind_R7O2 = 135 
  INTEGER, PARAMETER :: ind_MVN2 = 136 
  INTEGER, PARAMETER :: ind_RCO3 = 137 
  INTEGER, PARAMETER :: ind_PO2 = 138 
  INTEGER, PARAMETER :: ind_PIO2 = 139 
  INTEGER, PARAMETER :: ind_LIO2 = 140 
  INTEGER, PARAMETER :: ind_IALD = 141 
  INTEGER, PARAMETER :: ind_PRN1 = 142 
  INTEGER, PARAMETER :: ind_INO2 = 143 
  INTEGER, PARAMETER :: ind_R4O2 = 144 
  INTEGER, PARAMETER :: ind_ATO2 = 145 
  INTEGER, PARAMETER :: ind_BUTE = 146 
  INTEGER, PARAMETER :: ind_MEK = 147 
  INTEGER, PARAMETER :: ind_ALD2 = 148 
  INTEGER, PARAMETER :: ind_HAC = 149 
  INTEGER, PARAMETER :: ind_R4N2 = 150 
  INTEGER, PARAMETER :: ind_MVN1 = 151 
  INTEGER, PARAMETER :: ind_HCHO = 152 
  INTEGER, PARAMETER :: ind_IAO2 = 153 
  INTEGER, PARAMETER :: ind_MGLY = 154 
  INTEGER, PARAMETER :: ind_KO2 = 155 
  INTEGER, PARAMETER :: ind_ETO2 = 156 
  INTEGER, PARAMETER :: ind_RIO1 = 157 
  INTEGER, PARAMETER :: ind_ISNR = 158 
  INTEGER, PARAMETER :: ind_GLYC = 159 
  INTEGER, PARAMETER :: ind_RCHO = 160 
  INTEGER, PARAMETER :: ind_MACR = 161 
  INTEGER, PARAMETER :: ind_MAO3 = 162 
  INTEGER, PARAMETER :: ind_NO2 = 163 
  INTEGER, PARAMETER :: ind_MVK = 164 
  INTEGER, PARAMETER :: ind_NO3 = 165 
  INTEGER, PARAMETER :: ind_MO2 = 166 
  INTEGER, PARAMETER :: ind_HO2 = 167 
  INTEGER, PARAMETER :: ind_MCO3 = 168 
  INTEGER, PARAMETER :: ind_RIO2 = 169 
  INTEGER, PARAMETER :: ind_IPO2 = 170 
  INTEGER, PARAMETER :: ind_VRO2 = 171 
  INTEGER, PARAMETER :: ind_OH = 172 
  INTEGER, PARAMETER :: ind_O3 = 173 
  INTEGER, PARAMETER :: ind_MRO2 = 174 
  INTEGER, PARAMETER :: ind_NO = 175 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_x = 176 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER, PARAMETER :: indf_x = 1 

! NJVRP - Length of sparse Jacobian JVRP
  INTEGER, PARAMETER :: NJVRP = 969 

! NSTOICM - Length of Sparse Stoichiometric Matrix
  INTEGER, PARAMETER :: NSTOICM = 2353 

END MODULE gasphs_Parameters

