#!/bin/bash

#PBS -N test 
#PBS -l walltime=24:00:00
##PBS -l nodes=5:ppn=12
#PBS -l nodes=60
#PBS -q esp

# load required modules
. /etc/profile.d/modules.sh
module purge 
module load openmpi/1.5.3/intel/2011 
module load netcdf/4.1.2/intel/2011

# definition of shared library
export LD_LIBRARY_PATH=$ESMF_LIB:${LD_LIBRARY_PATH}

# run coupled model
cd /home/netapp/clima-users/users/uturunco/CAS/run.roms/coupled/cas.cplwice
mpirun ./Bin/regcmMPI regcm.in_CAS50km cas.in > regcmout.txt
