! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The Reaction Rates File
! 
! Generated by KPP-2.2 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gasphs_Rates.f90
! Time                 : Tue Mar 10 15:03:35 2009
! Working directory    : /scratch/ASHALABY/KPP/COMPARE/SILLMAN
! Equation file        : gasphs.kpp
! Output root filename : gasphs
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gasphs_Rates

  USE gasphs_Parameters
  USE gasphs_Global
  IMPLICIT NONE

CONTAINS



! Begin Rate Law Functions from KPP_HOME/util/UserRateLaws

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  User-defined Rate Law functions
!  Note: the default argument type for rate laws, as read from the equations file, is single precision
!        but all the internal calculations are performed in double precision
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!~~~>  Arrhenius
   REAL(kind=dp) FUNCTION ARR( A0,B0,C0 )
      REAL A0,B0,C0      
      ARR =  DBLE(A0) * EXP(-DBLE(B0)/TEMP) * (TEMP/300.0_dp)**DBLE(C0)
   END FUNCTION ARR        

!~~~> Simplified Arrhenius, with two arguments
!~~~> Note: The argument B0 has a changed sign when compared to ARR
   REAL(kind=dp) FUNCTION ARR2( A0,B0 )
      REAL A0,B0           
      ARR2 =  DBLE(A0) * EXP( DBLE(B0)/TEMP )              
   END FUNCTION ARR2          

   REAL(kind=dp) FUNCTION EP2(A0,C0,A2,C2,A3,C3)
      REAL A0,C0,A2,C2,A3,C3
      REAL(kind=dp) K0,K2,K3            
      K0 = DBLE(A0) * EXP(-DBLE(C0)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      K3 = DBLE(A3) * EXP(-DBLE(C3)/TEMP)
      K3 = K3*CFACTOR*1.0E6_dp
      EP2 = K0 + K3/(1.0_dp+K3/K2 )
   END FUNCTION EP2

   REAL(kind=dp) FUNCTION EP3(A1,C1,A2,C2) 
      REAL A1, C1, A2, C2
      REAL(kind=dp) K1, K2      
      K1 = DBLE(A1) * EXP(-DBLE(C1)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      EP3 = K1 + K2*(1.0E6_dp*CFACTOR)
   END FUNCTION EP3 

   REAL(kind=dp) FUNCTION FALL ( A0,B0,C0,A1,B1,C1,CF)
      REAL A0,B0,C0,A1,B1,C1,CF
      REAL(kind=dp) K0, K1     
      K0 = DBLE(A0) * EXP(-DBLE(B0)/TEMP)* (TEMP/300.0_dp)**DBLE(C0)
      K1 = DBLE(A1) * EXP(-DBLE(B1)/TEMP)* (TEMP/300.0_dp)**DBLE(C1)
      K0 = K0*CFACTOR*1.0E6_dp
      K1 = K0/K1
      FALL = (K0/(1.0_dp+K1))*   &
           DBLE(CF)**(1.0_dp/(1.0_dp+(LOG10(K1))**2))
   END FUNCTION FALL

  !---------------------------------------------------------------------------

 ! ELEMENTAL
  REAL(kind=dp) FUNCTION k_3rd(temp,cair,k0_300K,n,kinf_300K,m,fc)

    INTRINSIC LOG10

    REAL(kind=dp), INTENT(IN) :: temp      ! temperature [K]
    REAL(kind=dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL, INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL, INTENT(IN) :: n         ! exponent for low pressure limit
    REAL, INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL, INTENT(IN) :: m         ! exponent for high pressure limit
    REAL, INTENT(IN) :: fc        ! broadening factor (usually fc=0.6)
    REAL(kind=dp) :: zt_help, k0_T, kinf_T, k_ratio

    zt_help = 300._dp/temp
    k0_T    = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    k_3rd   = k0_T/(1._dp+k_ratio)*fc**(1._dp/(1._dp+LOG10(k_ratio)**2))

  END FUNCTION k_3rd

  !---------------------------------------------------------------------------

 ! ELEMENTAL
  REAL(kind=dp) FUNCTION k_arr (k_298,tdep,temp)
    ! Arrhenius function

    REAL,     INTENT(IN) :: k_298 ! k at T = 298.15K
    REAL,     INTENT(IN) :: tdep  ! temperature dependence
    REAL(kind=dp), INTENT(IN) :: temp  ! temperature

    INTRINSIC EXP

    k_arr = k_298 * EXP(tdep*(1._dp/temp-3.3540E-3_dp)) ! 1/298.15=3.3540e-3

  END FUNCTION k_arr

!The Following Rate reaction function from Sandy Sillman Box model
!Added by A. Shalaby Mar-2009

  REAL(kind=dp) FUNCTION RATE0(A0,B0)
  REAL A0,B0
  RATE0 = DBLE(A0)*exp(-DBLE(B0)/TEMP)
  END FUNCTION      RATE0  

  REAL(kind=dp) FUNCTION RATE1(A0,B0)
  REAL A0,B0
  RATE1 = DBLE(A0)*exp(-DBLE(B0)*(1./TEMP-0.0033557047))
  END FUNCTION      RATE1  

  REAL(kind=dp) FUNCTION RATE2(A0,B0,C0)
  REAL A0,B0,C0
  RATE2 =DBLE(A0)*EXP(-DBLE(B0)/TEMP)*(TEMP/300.0_dp)**DBLE(C0)
  END FUNCTION      RATE2  
 
  REAL(kind=dp) FUNCTION RATE3(A0,B0,C0,D0,E0)
  REAL A0,B0,C0,D0,E0
  REAL(KIND=8) tempx,denx
  tempx = TEMP
  denx  = C_M
  RATE3 = bod(DBLE(A0),DBLE(B0),DBLE(C0),DBLE(D0),DBLE(E0),tempx,denx )
  END FUNCTION      RATE3 

  REAL(kind=dp) FUNCTION RATE4(A0,B0,C0,D0,E0,F0,G0)
  REAL A0,B0
  REAL C0,D0,E0,F0,G0
  REAL(KIND=8) tempx,denx
  tempx = TEMP
  denx  = C_M
  RATE4 = bod(DBLE(C0),DBLE(D0),DBLE(E0),DBLE(F0),DBLE(G0),tempx,denx )
  RATE4 = RATE4*A0*exp(-B0/tempx)
  END FUNCTION      RATE4  

  REAL(kind=dp) FUNCTION RATE5(A0,B0,C0)
  REAL A0,B0
  REAL C0
  RATE5 = DBLE(A0)*exp(-DBLE(B0)/TEMP)
  RATE5 = RATE5* (1.- ytn(DBLE(C0),TEMP,C_M) )
  END FUNCTION      RATE5  

  REAL(kind=dp) FUNCTION RATE6(A0,B0,C0)
  REAL A0,B0
  REAL C0
  RATE6 = DBLE(A0)*exp(-DBLE(B0)/TEMP)
  RATE6 = RATE6* (ytn(DBLE(C0),TEMP,C_M) )
  END FUNCTION      RATE6  

  REAL(kind=dp) FUNCTION RATE7(A0,B0,C0,D0,E0,F0)
  REAL A0,B0,C0,D0,E0,F0
  RATE7 = DBLE(A0)*exp(-DBLE(B0)/TEMP)
  RATE7 = RATE7*(DBLE(C0) + DBLE(D0)*C_M)/(DBLE(E0) + DBLE(F0)*C_M)
  END FUNCTION      RATE7  

  REAL(kind=dp) FUNCTION RATE8(A0,B0,C0,D0,E0)
  REAL A0,B0,C0,D0,E0
  RATE8 = DBLE(A0)*exp(-DBLE(B0)/TEMP)
  RATE8 = RATE8 / ( 1. + (DBLE(C0) + DBLE(E0)*C_M )*exp(-DBLE(D0)/TEMP)    )
  END FUNCTION      RATE8  

  REAL(kind=dp) FUNCTION RATE9(A0,B0,C0,D0)
  USE gasphs_Parameters
  REAL A0,B0,C0,D0

  RATE9 = DBLE(A0)*exp(-DBLE(B0)/TEMP)
  RATE9 = RATE9 + DBLE(C0)*exp(-DBLE(D0)/TEMP) * C_M
  RATE9 = RATE9 *  (1. + DBLE(C0)*exp(-DBLE(D0)/TEMP) * VAR(ind_H2O)  )

  END FUNCTION      RATE9  

  REAL(kind=dp) FUNCTION RATE10(A0,B0,C0,D0,E0,F0)
  REAL A0,B0,C0,D0,E0,F0
  REAL(kind=8) beta,gamma

  RATE10 = DBLE(A0)*exp(-DBLE(B0)/TEMP)
  beta   = DBLE(C0)*exp(-DBLE(D0)/TEMP)*C_M
  gamma  = DBLE(E0)*exp(-DBLE(F0)/TEMP)
  RATE10  = RATE10 +beta*gamma/(beta+gamma)
  END FUNCTION      RATE10  

  REAL(kind=dp) FUNCTION RATE11(A0,B0,C0,D0,E0)
  REAL A0,B0,C0,D0,E0
  REAL(kind=8) beta
  RATE11  = DBLE(A0)*exp(-DBLE(B0)/TEMP)
  beta    = DBLE(D0)*exp(-DBLE(E0)/TEMP)
  RATE11  = RATE11 / (1. +DBLE(C0)* (TEMP/300.)**beta   )
  END FUNCTION      RATE11  

  REAL(kind=dp) FUNCTION RATE12(A0,B0,C0,D0)
  REAL A0,B0,C0,D0
  RATE12 = DBLE(A0)*exp(-DBLE(B0)/TEMP) + DBLE(C0)*exp(-DBLE(D0)/TEMP)
  END FUNCTION      RATE12  


  FUNCTION bod(u,b,c,d,e, tempx, denx)
  IMPLICIT NONE
  double precision b       ! ko(300) = Low pressure limit at 300 K.
  double precision c       ! exponent for temperature, -n in JPL.
  double precision d       ! kinf(300), High pressure limit at 300 K
  double precision e       ! exponent for temperature, -m in JPL.
  double precision u       ! Fc, base for log-T-P adjustment (0.6)
  double precision tempx   ! temperature K
  double precision denx    ! density, molec/cm3
  double precision bod     ! Output reaction rate cm3-sec
! LOCAL VARIABLES:  INTERNAL
  double precision f1            ! Interim parameter
  double precision f2            ! Interim parameter
  double precision ee            ! Interim parameter
  f1=b*((tempx/300.)**c)*denx
  f2=f1/( d * ((tempx/300.)**e))
  ee= 1. / ( 1 + (log10(f2))**2. )

  bod = (f1/(1+f2) ) * u ** ee
  return
  END FUNCTION bod

  FUNCTION ytn(c, tempx, denx)
  IMPLICIT NONE
  double precision c       ! Number of carbon atoms in RO2
  double precision tempx   ! temperature K
  double precision denx    ! density, molec/cm3
  double precision ytn     ! Output: RNO3 yield from RO2+NO

! LOCAL VARIABLES:  INTERNAL  
  double precision x
  double precision y
  double precision z
  double precision par
  PARAMETER (par=4.3D-25)
  x=par*tempx*exp(1.08*c)*denx*(300./tempx)**5.05
  y=0.384*(300./tempx)**4.16
  z=1./ ( 1.+ (log10(x/y))**2. )
  ytn= ( x / (1.+ x/y ))*(0.467**z)
  return
  END FUNCTION ytn
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  End of User-defined Rate Law functions
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! End Rate Law Functions from KPP_HOME/util/UserRateLaws


! Begin INLINED Rate Law Functions


! End INLINED Rate Law Functions

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_SUN - update SUN light using TIME
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  SUBROUTINE Update_SUN()
      !USE gasphs_Parameters
      !USE gasphs_Global

    IMPLICIT NONE

    REAL(kind=dp) :: SunRise, SunSet
    REAL(kind=dp) :: Thour, Tlocal, Ttmp 
    ! PI - Value of pi
    REAL(kind=dp), PARAMETER :: PI = 3.14159265358979d0
    
    SunRise = 4.5_dp 
    SunSet  = 19.5_dp 
    Thour = TIME/3600.0_dp 
    Tlocal = Thour - (INT(Thour)/24)*24

    IF ((Tlocal>=SunRise).AND.(Tlocal<=SunSet)) THEN
       Ttmp = (2.0*Tlocal-SunRise-SunSet)/(SunSet-SunRise)
       IF (Ttmp.GT.0) THEN
          Ttmp =  Ttmp*Ttmp
       ELSE
          Ttmp = -Ttmp*Ttmp
       END IF
       SUN = ( 1.0_dp + COS(PI*Ttmp) )/2.0_dp 
    ELSE
       SUN = 0.0_dp 
    END IF

 END SUBROUTINE Update_SUN

! End of Update_SUN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_RCONST - function to update rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_RCONST ( )




! Begin INLINED RCONST


! End INLINED RCONST

  RCONST(1) = (RATE0(3.0E-12,1500.))
  RCONST(2) = (RATE0(1.7E-12,940.))
  RCONST(3) = (RATE0(1.0E-14,490.))
  RCONST(4) = (RATE0(1.2E-13,2450.))
  RCONST(5) = (RATE0(2.9E-16,1000.))
  RCONST(6) = (RATE0(4.2E-12,240.))
  RCONST(7) = (RATE3(0.60,6.900E-31,-1.0,2.600E-11,-0.0))
  RCONST(8) = (RATE0(4.800E-11,-250.))
  RCONST(9) = (RATE0(2.9E-12,160.))
  RCONST(10) = (RATE0(3.5E-12,-250.))
  RCONST(11) = (RATE9(2.300E-13,-600.,1.700E-33,-1000.))
  RCONST(12) = (RATE0(5.500E-12,2000.))
  RCONST(13) = (RATE7(1.500E-13,0.,1.0,2.400E-20,1.0,0.0))
  RCONST(14) = (RATE0(2.450E-12,1775.))
  RCONST(15) = (RATE0(2.800E-12,-300.))
  RCONST(16) = (RATE8(4.100E-13,-750.,2.000E-03,-1160.,0.0))
  RCONST(17) = (RATE8(4.100E-13,-750.,4.980E+02,1160.,0.0))
  RCONST(18) = (RATE8(9.500E-14,-390.,2.620E+01,1130.,0.0))
  RCONST(19) = (RATE8(9.500E-14,-390.,4.000E-02,-1130.,0.0))
  RCONST(20) = (RATE0(3.800E-12,-200.))
  RCONST(21) = (RATE0(9.000E-12,0.0))
  RCONST(22) = (RATE3(0.60,2.000E-30,-3.0,2.500E-11,-0.0))
  RCONST(23) = (RATE10(2.410E-14,-460.,6.510E-34,-1335.,2.690E-17,-2199.))
  RCONST(24) = (RATE3(0.60,7.000E-31,-2.6,3.600E-11,-0.1))
  RCONST(25) = (RATE0(1.800E-11,390.))
  RCONST(26) = (RATE3(0.60,1.800E-31,-3.2,4.700E-12,-1.4))
  RCONST(27) = (RATE4(1.0,10900.,0.60,8.640E-05,-3.2,2.240E+15,-1.4))
  RCONST(28) = (RATE0(1.300E-12,-380.))
  RCONST(29) = (RATE0(3.500E-12,0.))
  RCONST(30) = (RATE0(1.500E-11,-170.))
  RCONST(31) = (RATE0(2.200E-11,0.))
  RCONST(32) = (RATE3(0.60,2.000E-30,-4.4,1.400E-12,-0.7))
  RCONST(33) = (RATE4(1.0,10990.,0.60,6.670E-04,-4.4,4.670E+14,-0.7))
  RCONST(34) = (RATE0(4.000E-13,0.))
  RCONST(35) = (RATE0(7.300E-12,620.))
  RCONST(36) = (RATE0(4.500E-14,1260.))
  RCONST(37) = (RATE0(5.800E-16,0.))
  RCONST(38) = (RATE0(5.600E-12,-270.))
  RCONST(39) = (RATE0(1.400E-12,1860.))
  RCONST(40) = (RATE3(0.60,8.500E-29,-6.5,1.100E-11,-1.0))
  RCONST(41) = (RATE4(1.075E+28,14000.,0.60,8.500E-29,-6.5,1.100E-11,-1.0))
  RCONST(42) = (RATE0(8.100E-12,-270.))
  RCONST(43) = (RATE0(8.700E-12,1070.))
  RCONST(44) = (RATE0(2.700E-12,-350.))
  RCONST(45) = (RATE11(7.600E-12,585.,5.870E+00,-0.640,816.))
  RCONST(46) = (RATE11(7.600E-12,585.,1.700E-01,0.640,-816.))
  RCONST(47) = (RATE0(2.700E-12,-350.))
  RCONST(48) = (RATE0(2.700E-12,-350.))
  RCONST(49) = (RATE2(1.647E-12,-162.,2.0))
  RCONST(50) = (RATE5(2.700E-12,-350.,4.5))
  RCONST(51) = (RATE6(2.700E-12,-350.,4.5))
  RCONST(52) = (RATE0(2.700E-12,-350.))
  RCONST(53) = (RATE0(2.800E-12,-300.))
  RCONST(54) = (RATE0(2.700E-12,-350.))
  RCONST(55) = (RATE5(2.700E-12,-350.,5.0))
  RCONST(56) = (RATE6(2.700E-12,-350.,5.0))
  RCONST(57) = (RATE5(2.700E-12,-350.,5.0))
  RCONST(58) = (RATE6(2.700E-12,-350.,5.0))
  RCONST(59) = (RATE0(2.700E-12,-350.))
  RCONST(60) = (RATE0(2.700E-12,-350.))
  RCONST(61) = (RATE5(2.700E-12,-350.,4.0))
  RCONST(62) = (RATE6(2.700E-12,-350.,4.0))
  RCONST(63) = (RATE5(2.700E-12,-350.,4.0))
  RCONST(64) = (RATE6(2.700E-12,-350.,4.0))
  RCONST(65) = (RATE0(2.700E-12,-350.))
  RCONST(66) = (RATE0(2.700E-12,-350.))
  RCONST(67) = (RATE0(2.700E-12,-350.))
  RCONST(68) = (RATE0(2.700E-12,-350.))
  RCONST(69) = (RATE0(2.700E-12,-350.))
  RCONST(70) = (RATE0(2.800E-12,3280.))
  RCONST(71) = (RATE0(1.300E-12,0.))
  RCONST(72) = (RATE0(4.000E-13,-200.))
  RCONST(73) = (RATE0(5.100E-12,-405.))
  RCONST(74) = (RATE3(0.60,9.000E-28,-8.9,7.700E-12,-0.2))
  RCONST(75) = (RATE3(0.60,9.000E-28,-8.9,7.700E-12,-0.2))
  RCONST(76) = (RATE3(0.60,9.000E-28,-8.9,7.700E-12,-0.2))
  RCONST(77) = (RATE4(1.111E+28,14000.,0.60,9.000E-28,-8.9,7.700E-12,-0.2))
  RCONST(78) = (RATE4(1.111E+28,14000.,0.60,9.000E-28,-8.9,7.700E-12,-0.2))
  RCONST(79) = (RATE0(6.700E-12,-340.))
  RCONST(80) = (RATE0(6.700E-12,-340.))
  RCONST(81) = (RATE0(6.700E-12,-340.))
  RCONST(82) = (RATE0(1.820E-12,1680.))
  RCONST(83) = (RATE12(3.820E-11,2000.,1.330E-13,0.))
  RCONST(84) = (RATE0(5.920E-13,0.))
  RCONST(85) = (RATE0(5.920E-13,0.))
  RCONST(86) = (RATE0(7.400E-13,-700.))
  RCONST(87) = (RATE0(7.400E-13,-700.))
  RCONST(88) = (RATE0(8.600E-13,-700.))
  RCONST(89) = (RATE0(7.400E-13,-700.))
  RCONST(90) = (RATE0(7.400E-13,-700.))
  RCONST(91) = (RATE0(7.400E-13,-700.))
  RCONST(92) = (RATE0(7.400E-13,-700.))
  RCONST(93) = (RATE0(7.400E-13,-700.))
  RCONST(94) = (RATE0(7.400E-13,-700.))
  RCONST(95) = (RATE0(7.400E-13,-700.))
  RCONST(96) = (RATE0(7.400E-13,-700.))
  RCONST(97) = (RATE0(7.400E-13,-700.))
  RCONST(98) = (RATE0(7.400E-13,-700.))
  RCONST(99) = (RATE0(7.400E-13,-700.))
  RCONST(100) = (RATE0(7.400E-13,-700.))
  RCONST(101) = (RATE2(2.280E-13,-503.,2.0))
  RCONST(102) = (RATE0(3.000E-13,0.))
  RCONST(103) = (RATE0(8.000E-16,0.))
  RCONST(104) = (RATE0(8.370E-14,0.))
  RCONST(105) = (RATE0(8.370E-14,0.))
  RCONST(106) = (RATE0(7.500E-13,-500.))
  RCONST(107) = (RATE0(8.370E-14,0.))
  RCONST(108) = (RATE0(8.370E-14,0.))
  RCONST(109) = (RATE0(8.370E-14,0.))
  RCONST(110) = (RATE0(8.370E-14,0.))
  RCONST(111) = (RATE0(8.370E-14,0.))
  RCONST(112) = (RATE0(8.370E-14,0.))
  RCONST(113) = (RATE0(8.370E-14,0.))
  RCONST(114) = (RATE0(8.370E-14,0.))
  RCONST(115) = (RATE0(8.370E-14,0.))
  RCONST(116) = (RATE0(8.370E-14,0.))
  RCONST(117) = (RATE0(8.370E-14,0.))
  RCONST(118) = (RATE0(8.370E-14,0.))
  RCONST(119) = (RATE0(6.900E-12,230.))
  RCONST(120) = (RATE0(4.600E-12,-70.))
  RCONST(121) = (RATE0(6.800E-14,0.))
  RCONST(122) = (RATE0(7.400E-13,-700.))
  RCONST(123) = (RATE0(7.400E-13,-700.))
  RCONST(124) = (RATE0(7.400E-13,-700.))
  RCONST(125) = (RATE8(4.300E-13,-1040.,3.700E+01,660.,0.0))
  RCONST(126) = (RATE8(4.300E-13,-1040.,2.700E-02,660.,0.0))
  RCONST(127) = (RATE0(4.300E-13,-1040.))
  RCONST(128) = (RATE0(4.300E-13,-1040.))
  RCONST(129) = (RATE0(4.300E-13,-1040.))
  RCONST(130) = (RATE3(0.50,8.000E-27,3.5,3.000E-11,1.0))
  RCONST(131) = (RATE0(5.500E-15,1880.))
  RCONST(132) = (RATE4(1.111E+28,14000.,0.60,9.000E-28,-8.9,7.700E-12,-0.2))
  RCONST(133) = (RATE0(3.200E-11,0.))
  RCONST(134) = (RATE0(8.200E-18,0.))
  RCONST(135) = (RATE0(1.000E-11,0.))
  RCONST(136) = (RATE0(4.590E-13,1156.))
  RCONST(137) = (RATE7(1.100E-11,0.,3.500E+18,2.090E-01,3.500E+18,4.180E-01))
  RCONST(138) = (RATE0(1.700E-11,0.))
  RCONST(139) = (RATE7(1.400E-12,1860.,3.500E+18,2.090E-01,3.500E+18,4.180E-01))
  RCONST(140) = (RATE0(1.400E-12,1860.))
  RCONST(141) = (RATE0(2.700E-11,-390.))
  RCONST(142) = (RATE0(4.130E-12,-452.))
  RCONST(143) = (RATE0(1.860E-11,-175.))
  RCONST(144) = (RATE0(3.000E-12,0.))
  RCONST(145) = (RATE0(1.680E-12,-500.))
  RCONST(146) = (RATE0(1.870E-13,-500.))
  RCONST(147) = (RATE0(1.680E-12,-500.))
  RCONST(148) = (RATE0(1.870E-13,-500.))
  RCONST(149) = (RATE0(1.050E-14,2000.))
  RCONST(150) = (RATE0(4.000E-15,2000.))
  RCONST(151) = (RATE0(4.400E-15,2500.))
  RCONST(152) = (RATE0(3.030E-12,446.))
  RCONST(153) = (RATE0(2.000E-14,0.))
  RCONST(154) = (RATE0(1.000E-14,0.))
  RCONST(155) = (RATE0(1.870E-13,-500.))
  RCONST(156) = (RATE0(1.870E-13,-500.))
  RCONST(157) = (RATE0(1.870E-13,-500.))
  RCONST(158) = (RATE0(1.870E-13,-500.))
  RCONST(159) = (RATE0(1.870E-13,-500.))
  RCONST(160) = (RATE0(1.870E-13,-500.))
  RCONST(161) = (RATE0(8.000E-12,-380.))
  RCONST(162) = (RATE0(8.000E-12,-380.))
  RCONST(163) = (RATE0(3.800E-12,-200.))
  RCONST(164) = (RATE0(3.800E-12,-200.))
  RCONST(165) = (RATE0(3.800E-12,-200.))
  RCONST(166) = (RATE0(3.800E-12,-200.))
  RCONST(167) = (RATE0(3.800E-12,-200.))
  RCONST(168) = (RATE0(3.800E-12,-200.))
  RCONST(169) = (RATE0(3.800E-12,-200.))
  RCONST(170) = (RATE0(8.000E-12,-380.))
  RCONST(171) = (RATE0(8.000E-12,-380.))
  RCONST(172) = (RATE0(8.000E-12,-380.))
  RCONST(173) = (RATE0(8.000E-12,-380.))
  RCONST(174) = (RATE0(8.000E-12,-380.))
  RCONST(175) = (RATE0(8.000E-12,-380.))
  RCONST(176) = (RATE0(3.800E-12,-200.))
  RCONST(177) = (RATE0(1.400E-15,2100.))
  RCONST(178) = (RATE0(1.400E-15,2100.))
  RCONST(179) = (RATE0(1.400E-15,2100.))
  RCONST(180) = (RATE0(1.400E-15,2100.))
  RCONST(181) = (RATE0(1.400E-15,2100.))
  RCONST(182) = (RATE0(1.400E-15,2100.))
  RCONST(183) = (RATE0(1.400E-15,2100.))
  RCONST(184) = (RATE0(1.400E-15,2100.))
  RCONST(185) = (RATE0(1.400E-18,0.))
  RCONST(186) = (RATE0(3.700E-11,0.))
  RCONST(187) = (RATE0(6.160E-15,1814.))
  RCONST(188) = (RATE0(2.500E-12,-500.))
  RCONST(189) = (RATE0(1.800E-12,-500.))
  RCONST(190) = (RATE0(2.000E-13,-500.))
  RCONST(191) = (RATE0(1.680E-12,-500.))
  RCONST(192) = (RATE0(1.680E-12,-500.))
  RCONST(193) = (RATE0(1.680E-12,-500.))
  RCONST(194) = (RATE0(1.680E-12,-500.))
  RCONST(195) = (RATE0(1.680E-12,-500.))
  RCONST(196) = (RATE0(1.680E-12,-500.))
  RCONST(197) = (RATE0(1.680E-12,-500.))
  RCONST(198) = (RATE0(1.680E-12,-500.))
  RCONST(199) = (RATE0(1.680E-12,-500.))
  RCONST(200) = (RATE0(1.680E-12,-500.))
  RCONST(201) = (RATE0(1.680E-12,-500.))
  RCONST(202) = (RATE0(1.680E-12,-500.))
  RCONST(203) = (RATE0(1.680E-12,-500.))
  RCONST(204) = (RATE0(1.680E-12,-500.))
  RCONST(205) = (RATE0(1.680E-12,-500.))
  RCONST(206) = (RATE0(1.870E-13,-500.))
  RCONST(207) = (RATE0(1.870E-13,-500.))
  RCONST(208) = (RATE0(1.870E-13,-500.))
  RCONST(209) = (RATE0(1.870E-13,-500.))
  RCONST(210) = (RATE0(1.870E-13,-500.))
  RCONST(211) = (RATE0(1.870E-13,-500.))
  RCONST(212) = (RATE0(1.870E-13,-500.))
  RCONST(213) = (RATE0(1.870E-13,-500.))
  RCONST(214) = (RATE0(1.870E-13,-500.))
  RCONST(215) = (RATE0(1.870E-13,-500.))
  RCONST(216) = (RATE0(1.870E-13,-500.))
  RCONST(217) = (RATE0(1.870E-13,-500.))
  RCONST(218) = (RATE0(1.870E-13,-500.))
  RCONST(219) = (RATE0(1.870E-13,-500.))
  RCONST(220) = (RATE0(1.870E-13,-500.))
  RCONST(221) = (RATE0(1.680E-12,-500.))
  RCONST(222) = (RATE0(1.870E-13,-500.))
  RCONST(223) = (RATE0(2.500E-12,-500.))
  RCONST(224) = (RATE0(2.500E-12,-500.))
  RCONST(225) = (RATE0(2.500E-12,-500.))
  RCONST(226) = (RATE0(8.500E-13,2450.))
! RCONST(227) = constant rate coefficient
! RCONST(228) = constant rate coefficient
! RCONST(229) = constant rate coefficient
! RCONST(230) = constant rate coefficient
!  RCONST(231) = (jval_O31D/310.7534872591496)
  RCONST(231) = (jval_O31D/(1.+0.13181*C_M/VAR(ind_H2O)))
  RCONST(232) = (jval_NO2)
  RCONST(233) = (jval_H2O2)
  RCONST(234) = (5.E-4*jval_NO2)
  RCONST(235) = (jval_CH2Oa)
  RCONST(236) = (jval_CH2Ob)
  RCONST(237) = (jval_HNO3)
  RCONST(238) = (jval_HNO2)
  RCONST(239) = (jval_HNO4)
  RCONST(240) = (jval_NO3b)
  RCONST(241) = (jval_NO3a)
  RCONST(242) = (jval_N2O5b)
  RCONST(243) = (jval_CH3CHOa)
  RCONST(244) = (jval_PAN)
  RCONST(245) = (jval_C2H5CHO)
  RCONST(246) = (jval_CH3COCH3)
  RCONST(247) = (7.762E-05*jval_NO2)
  RCONST(248) = (7.413E-04*jval_NO2)
  RCONST(249) = (jval_CHOCHO)
  RCONST(250) = (1.900E-02*jval_NO2)
  RCONST(251) = (1.692E-03*jval_NO2)
  RCONST(252) = (5.640E-04*jval_NO2)
  RCONST(253) = (5.640E-04*jval_NO2)
  RCONST(254) = (8.436E-04*jval_NO2)
  RCONST(255) = (8.436E-04*jval_NO2)
  RCONST(256) = (5.000E-04*jval_NO2)
  RCONST(257) = (5.000E-04*jval_NO2)
  RCONST(258) = (5.000E-04*jval_NO2)
  RCONST(259) = (5.000E-04*jval_NO2)
  RCONST(260) = (5.000E-04*jval_NO2)
  RCONST(261) = (5.000E-04*jval_NO2)
  RCONST(262) = (5.000E-04*jval_NO2)
  RCONST(263) = (5.000E-04*jval_NO2)
  RCONST(264) = (5.000E-04*jval_NO2)
  RCONST(265) = (5.000E-04*jval_NO2)
  RCONST(266) = (5.000E-04*jval_NO2)
  RCONST(267) = (5.000E-04*jval_NO2)
  RCONST(268) = (5.000E-04*jval_NO2)
  RCONST(269) = (5.000E-04*jval_NO2)
  RCONST(270) = (5.000E-04*jval_NO2)
  RCONST(271) = (5.000E-04*jval_NO2)
  RCONST(272) = (4.590E-04*jval_NO2)
  RCONST(273) = (5.000E-04*jval_NO2)
  RCONST(274) = (RATE0(1.160E-12,0.))
  RCONST(275) = (RATE0(1.100E-12,650.))
  RCONST(276) = (RATE0(7.500E-12,651.))
  RCONST(277) = (RATE0(4.000E-24,0.))
  RCONST(278) = (RATE0(6.700E-15,-600.))
  RCONST(279) = (RATE0(3.000E-12,-280.))
  RCONST(280) = (RATE0(5.600E-15,-2300.))
  RCONST(281) = (RATE0(5.700E-14,-750.))
  RCONST(282) = (RATE0(2.400E+12,7000.))
  RCONST(283) = (RATE0(3.210E-11,0.))
  RCONST(284) = (RATE0(2.700E-12,-350.))
  RCONST(285) = (RATE0(7.400E-13,-700.))
  RCONST(286) = (RATE0(3.210E-11,0.))
  RCONST(287) = (RATE0(3.000E-15,2000.))
  RCONST(288) = (RATE0(2.000E-11,359.))
  RCONST(289) = (RATE5(4.901E-12,-180.,7.0))
  RCONST(290) = (RATE6(4.901E-12,-180.,7.0))
  RCONST(291) = (RATE0(4.901E-12,-180.))
  RCONST(292) = (RATE0(4.000E-14,0.))
  RCONST(293) = (RATE0(6.000E-17,0.))
  RCONST(294) = (RATE0(4.000E-12,0.))
  RCONST(295) = (RATE0(4.901E-12,-180.))
  RCONST(296) = (RATE0(4.901E-12,-180.))
  RCONST(297) = (RATE0(4.901E-12,-180.))
  RCONST(298) = (RATE0(3.000E-13,0.))
  RCONST(299) = (RATE0(1.660E-13,-1300.))
  RCONST(300) = (RATE0(1.660E-13,-1300.))
  RCONST(301) = (RATE0(1.660E-13,-1300.))
  RCONST(302) = (RATE0(1.660E-13,-1300.))
  RCONST(303) = (RATE0(1.000E-12,0.))
  RCONST(304) = (RATE0(4.901E-12,-180.))
  RCONST(305) = (RATE3(0.48,7.000E-29,3.1,9.000E-12,0.0))
  RCONST(306) = (RATE0(9.000E-12,0.))
  RCONST(307) = (RATE0(9.500E-15,2580.))
  RCONST(308) = (RATE0(1.100E-11,-549.))
  RCONST(309) = (RATE0(4.901E-12,-180.))
  RCONST(310) = (RATE0(7.500E-15,1050.))
  RCONST(311) = (RATE0(7.000E-12,0.))
  RCONST(312) = (RATE0(7.000E-13,0.))
  RCONST(313) = (RATE0(4.000E-18,0.))
  RCONST(314) = (RATE0(7.000E-12,0.))
  RCONST(315) = (RATE0(7.000E-13,0.))
  RCONST(316) = (RATE0(4.000E-18,0.))
  RCONST(317) = (RATE0(1.660E-13,-1300.))
  RCONST(318) = (RATE0(1.660E-13,-1300.))
  RCONST(319) = (RATE0(7.000E-14,0.))
  RCONST(320) = (RATE0(7.000E-14,0.))
  RCONST(321) = (RATE0(2.100E-13,0.))
  RCONST(322) = (RATE0(2.330E-12,193.))
  RCONST(323) = (RATE0(4.901E-12,-180.))
  RCONST(324) = (RATE0(1.180E-12,-338.))
  RCONST(325) = (RATE0(4.901E-12,-180.))
  RCONST(326) = (RATE0(4.901E-12,-180.))
  RCONST(327) = (RATE0(2.400E-11,0.))
  RCONST(328) = (RATE0(4.901E-12,-180.))
  RCONST(329) = (RATE0(2.800E-11,0.))
  RCONST(330) = (RATE0(4.250E-11,0.))
  RCONST(331) = (RATE0(7.000E-11,0.))
  RCONST(332) = (RATE0(1.500E-11,0.))
  RCONST(333) = (RATE0(3.000E-12,0.))
  RCONST(334) = (RATE0(4.901E-12,-180.))
  RCONST(335) = (RATE0(1.500E-11,0.))
  RCONST(336) = (RATE0(4.700E-12,0.))
  RCONST(337) = (RATE0(1.950E+16,13543.))
  RCONST(338) = (RATE0(2.000E-11,0.))
  RCONST(339) = (RATE0(2.000E-11,0.))
  RCONST(340) = (RATE0(2.000E-11,0.))
  RCONST(341) = (RATE0(2.000E-12,0.))
  RCONST(342) = (RATE0(1.000E-11,0.))
  RCONST(343) = (RATE0(1.500E-11,0.))
  RCONST(344) = (RATE0(1.000E-11,0.))
  RCONST(345) = (RATE0(3.000E-11,0.))
  RCONST(346) = (RATE0(1.500E-11,0.))
  RCONST(347) = (RATE0(3.000E-11,0.))
  RCONST(348) = (RATE0(4.700E-12,0.))
  RCONST(349) = (RATE0(4.700E-12,0.))
  RCONST(350) = (RATE0(4.700E-12,0.))
  RCONST(351) = (RATE0(4.700E-12,0.))
  RCONST(352) = (RATE0(1.950E+16,13543.))
  RCONST(353) = (RATE0(1.950E+16,13543.))
  RCONST(354) = (RATE0(1.950E+16,13543.))
  RCONST(355) = (RATE0(1.950E+16,13543.))
  RCONST(356) = (RATE0(2.000E-11,0.))
  RCONST(357) = (RATE0(2.000E-11,0.))
  RCONST(358) = (RATE0(2.000E-11,0.))
  RCONST(359) = (RATE0(2.000E-11,0.))
  RCONST(360) = (RATE0(2.000E-11,0.))
  RCONST(361) = (RATE0(2.000E-11,0.))
  RCONST(362) = (RATE0(2.000E-11,0.))
  RCONST(363) = (RATE0(2.000E-11,0.))
  RCONST(364) = (RATE0(2.000E-11,0.))
  RCONST(365) = (RATE0(2.000E-11,0.))
  RCONST(366) = (RATE0(2.000E-11,0.))
  RCONST(367) = (RATE0(2.000E-11,0.))
  RCONST(368) = (5.000E-03*jval_NO2)
  RCONST(369) = (3.000E-02*jval_NO2)
  RCONST(370) = (3.000E-02*jval_NO2)
  RCONST(371) = (RATE0(1.200E-11,0.))
  RCONST(372) = (RATE0(4.700E-12,0.))
  RCONST(373) = (RATE0(1.950E+16,13543.))
  RCONST(374) = (RATE0(2.000E-11,0.))
  RCONST(375) = (RATE0(2.000E-11,0.))
  RCONST(376) = (RATE0(3.750E-13,-980.))
  RCONST(377) = (RATE0(3.750E-13,-980.))
  RCONST(378) = (RATE0(3.750E-13,-980.))
  RCONST(379) = (RATE0(3.750E-13,-980.))
  RCONST(380) = (RATE0(3.750E-13,-980.))
  RCONST(381) = (RATE0(1.150E-12,-550.))
  RCONST(382) = (RATE0(1.150E-12,-550.))
  RCONST(383) = (RATE0(1.150E-12,-550.))
  RCONST(384) = (RATE0(1.150E-12,-550.))
  RCONST(385) = (RATE0(1.150E-12,-550.))
  RCONST(386) = (RATE0(1.150E-12,-550.))
  RCONST(387) = (RATE0(1.150E-12,-550.))
  RCONST(388) = (RATE0(1.150E-12,-550.))
  RCONST(389) = (RATE0(1.150E-12,-550.))
  RCONST(390) = (RATE0(1.150E-12,-550.))
  RCONST(391) = (RATE0(1.150E-12,-550.))
  RCONST(392) = (RATE0(1.150E-12,-550.))
  RCONST(393) = (RATE0(1.150E-12,-550.))
  RCONST(394) = (RATE0(1.150E-12,-550.))
  RCONST(395) = (RATE0(1.150E-12,-550.))
  RCONST(396) = (RATE0(1.150E-12,-550.))
  RCONST(397) = (RATE0(1.150E-12,-550.))
  RCONST(398) = (RATE0(1.210E-11,-444.))
  RCONST(399) = (RATE0(4.901E-12,-180.))
  RCONST(400) = (RATE0(1.660E-13,-1300.))
  RCONST(401) = (RATE0(1.010E-15,732.))
  RCONST(402) = (RATE0(1.190E-12,-490.))
  RCONST(403) = (RATE0(4.901E-12,-180.))
  RCONST(404) = (RATE0(4.200E-13,-180.))
  RCONST(405) = (RATE0(3.000E-12,0.))
  RCONST(406) = (RATE0(1.710E-10,0.))
  RCONST(407) = (RATE0(4.901E-12,-180.))
  RCONST(408) = (RATE0(3.210E-11,0.))
  RCONST(409) = (RATE0(1.660E-13,-1300.))
  RCONST(410) = (RATE0(2.000E-16,0.))
  RCONST(411) = (RATE0(1.220E-11,0.))
  RCONST(412) = (RATE0(6.190E-11,0.))
  RCONST(413) = (RATE0(4.901E-12,-180.))
  RCONST(414) = (RATE0(1.660E-13,-1300.))
  RCONST(415) = (RATE0(3.400E-12,-190.))
  RCONST(416) = (RATE0(3.400E-12,-190.))
  RCONST(417) = (RATE0(3.400E-12,-190.))
  RCONST(418) = (RATE0(3.400E-12,-190.))
  RCONST(419) = (RATE0(3.400E-12,-190.))
  RCONST(420) = (RATE0(3.400E-12,-190.))
  RCONST(421) = (RATE0(3.400E-12,-190.))
  RCONST(422) = (RATE0(3.400E-12,-190.))
  RCONST(423) = (RATE0(3.400E-12,-190.))
  RCONST(424) = (RATE0(3.400E-12,-190.))
  RCONST(425) = (RATE0(3.400E-12,-190.))
  RCONST(426) = (RATE0(3.400E-12,-190.))
  RCONST(427) = (RATE0(3.400E-12,-190.))
  RCONST(428) = (RATE0(3.400E-12,-190.))
  RCONST(429) = (1.000E-03*jval_NO2)
  RCONST(430) = (1.000E-03*jval_NO2)
  RCONST(431) = (1.000E-03*jval_NO2)
  RCONST(432) = (1.000E-03*jval_NO2)
  RCONST(433) = (1.000E-03*jval_NO2)
  RCONST(434) = (RATE0(3.400E-12,-190.))
  RCONST(435) = (5.000E-04*jval_NO2)
  RCONST(436) = (5.000E-04*jval_NO2)
  RCONST(437) = (5.000E-04*jval_NO2)
  RCONST(438) = (RATE0(3.400E-12,-190.))
  RCONST(439) = (RATE0(8.000E-21,0.))
  RCONST(440) = (RATE0(3.400E-12,-190.))
  RCONST(441) = (RATE0(8.000E-21,0.))
  RCONST(442) = (5.000E-04*jval_NO2)
  RCONST(443) = (5.000E-04*jval_NO2)
  RCONST(444) = (RATE0(7.500E-12,651.))
  RCONST(445) = (RATE0(7.500E-12,651.))
  RCONST(446) = (RATE0(7.500E-12,651.))
  RCONST(447) = (RATE0(7.500E-12,651.))
  RCONST(448) = (RATE0(7.500E-12,651.))
  RCONST(449) = (RATE0(7.500E-12,651.))
  RCONST(450) = (RATE0(7.500E-12,651.))
  RCONST(451) = (RATE0(2.800E-12,-530.))
  RCONST(452) = (RATE0(2.800E-12,-530.))
  RCONST(453) = (RATE0(3.690E-11,440.))
  RCONST(454) = (RATE0(3.690E-11,440.))
  RCONST(455) = (RATE0(2.800E-12,-530.))
  RCONST(456) = (RATE0(2.800E-12,-530.))
  RCONST(457) = (RATE0(2.800E-12,-530.))
  RCONST(458) = (RATE0(3.690E-11,440.))
  RCONST(459) = (RATE0(3.690E-11,440.))
  RCONST(460) = (RATE0(2.800E-12,-530.))
  RCONST(461) = (RATE0(2.800E-12,-530.))
  RCONST(462) = (RATE0(2.800E-12,-530.))
  RCONST(463) = (RATE0(3.690E-11,440.))
  RCONST(464) = (RATE0(3.690E-11,440.))
  RCONST(465) = (RATE0(2.800E-12,-530.))
  RCONST(466) = (RATE0(2.800E-12,-530.))
  RCONST(467) = (RATE0(2.800E-12,-530.))
  RCONST(468) = (RATE0(3.690E-11,440.))
  RCONST(469) = (RATE0(3.690E-11,440.))
  RCONST(470) = (RATE0(2.800E-12,-530.))
  RCONST(471) = (RATE0(2.800E-12,-530.))
  RCONST(472) = (RATE0(2.800E-12,-530.))
  RCONST(473) = (RATE0(3.690E-11,440.))
  RCONST(474) = (RATE0(3.690E-11,440.))
  RCONST(475) = (RATE0(2.800E-12,-530.))
  RCONST(476) = (RATE0(2.800E-12,-530.))
  RCONST(477) = (RATE0(2.800E-12,-530.))
  RCONST(478) = (RATE0(3.690E-11,440.))
  RCONST(479) = (RATE0(3.690E-11,440.))
  RCONST(480) = (RATE0(2.800E-12,-530.))
  RCONST(481) = (RATE0(2.800E-12,-530.))
  RCONST(482) = (RATE0(2.800E-12,-530.))
  RCONST(483) = (RATE0(3.690E-11,440.))
  RCONST(484) = (RATE0(3.690E-11,440.))
  RCONST(485) = (RATE0(2.800E-12,-530.))
  RCONST(486) = (RATE0(3.690E-11,440.))
  RCONST(487) = (RATE0(3.690E-11,440.))
  RCONST(488) = (RATE0(2.800E-12,-530.))
  RCONST(489) = (RATE0(2.800E-12,-530.))
  RCONST(490) = (RATE0(4.340E-14,-633.))
  RCONST(491) = (RATE0(4.340E-14,-633.))
  RCONST(492) = (RATE0(1.710E-13,-708.))
  RCONST(493) = (RATE0(1.710E-13,-708.))
  RCONST(494) = (RATE0(1.710E-13,-708.))
  RCONST(495) = (RATE0(1.710E-13,-708.))
  RCONST(496) = (RATE0(1.710E-13,-708.))
  RCONST(497) = (RATE0(1.710E-13,-708.))
  RCONST(498) = (RATE0(1.710E-13,-708.))
  RCONST(499) = (RATE0(1.710E-13,-708.))
  RCONST(500) = (RATE0(1.710E-13,-708.))
  RCONST(501) = (RATE0(1.710E-13,-708.))
  RCONST(502) = (RATE0(1.710E-13,-708.))
  RCONST(503) = (RATE0(1.710E-13,-708.))
  RCONST(504) = (RATE0(2.470E-13,-683.))
  RCONST(505) = (RATE0(2.470E-13,-683.))
  RCONST(506) = (RATE0(9.480E-13,-765.))
  RCONST(507) = (RATE0(9.480E-13,-765.))
  RCONST(508) = (RATE0(5.090E-13,-765.))
  RCONST(509) = (RATE0(5.090E-13,-765.))
  RCONST(510) = (RATE0(7.400E-13,-765.))
  RCONST(511) = (RATE0(7.400E-13,-765.))
  RCONST(512) = (RATE0(7.400E-13,-765.))
  RCONST(513) = (RATE0(7.400E-13,-765.))
  RCONST(514) = (RATE0(7.400E-13,-765.))
  RCONST(515) = (RATE0(7.400E-13,-765.))
  RCONST(516) = (RATE0(7.400E-13,-765.))
  RCONST(517) = (RATE0(7.400E-13,-765.))
  RCONST(518) = (RATE0(4.200E-13,0.))
  RCONST(519) = (RATE0(4.200E-13,0.))
  RCONST(520) = (RATE0(7.670E-13,0.))
  RCONST(521) = (RATE0(7.670E-13,0.))
  RCONST(522) = (RATE0(4.200E-13,0.))
  RCONST(523) = (RATE0(7.670E-13,0.))
  RCONST(524) = (RATE0(7.670E-13,0.))
  RCONST(525) = (RATE0(1.400E-12,0.))
  RCONST(526) = (RATE0(1.400E-12,0.))
  RCONST(527) = (RATE0(1.400E-12,0.))
  RCONST(528) = (RATE0(1.000E-12,0.))
  RCONST(529) = (RATE0(1.000E-12,0.))
  RCONST(530) = (RATE0(1.000E-12,0.))
  RCONST(531) = (RATE0(1.200E-11,260.))
  RCONST(532) = (RATE8(1.700E-42,-7810.,0.0,-7460.,1.150E-31))
  RCONST(533) = (RATE0(1.900E-13,-500.))
  RCONST(534) = (RATE3(0.60,3.000E-31,-3.3,1.500E-12,-0.0))
      
END SUBROUTINE Update_RCONST

! End of Update_RCONST function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_PHOTO - function to update photolytical rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_PHOTO ( )


   USE gasphs_Global

  RCONST(231) = (jval_O31D/310.7534872591496)
  RCONST(232) = (jval_NO2)
  RCONST(233) = (jval_H2O2)
  RCONST(234) = (5.E-4*jval_NO2)
  RCONST(235) = (jval_CH2Oa)
  RCONST(236) = (jval_CH2Ob)
  RCONST(237) = (jval_HNO3)
  RCONST(238) = (jval_HNO2)
  RCONST(239) = (jval_HNO4)
  RCONST(240) = (jval_NO3b)
  RCONST(241) = (jval_NO3a)
  RCONST(242) = (jval_N2O5b)
  RCONST(243) = (jval_CH3CHOa)
  RCONST(244) = (jval_PAN)
  RCONST(245) = (jval_C2H5CHO)
  RCONST(246) = (jval_CH3COCH3)
  RCONST(247) = (7.762E-05*jval_NO2)
  RCONST(248) = (7.413E-04*jval_NO2)
  RCONST(249) = (jval_CHOCHO)
  RCONST(250) = (1.900E-02*jval_NO2)
  RCONST(251) = (1.692E-03*jval_NO2)
  RCONST(252) = (5.640E-04*jval_NO2)
  RCONST(253) = (5.640E-04*jval_NO2)
  RCONST(254) = (8.436E-04*jval_NO2)
  RCONST(255) = (8.436E-04*jval_NO2)
  RCONST(256) = (5.000E-04*jval_NO2)
  RCONST(257) = (5.000E-04*jval_NO2)
  RCONST(258) = (5.000E-04*jval_NO2)
  RCONST(259) = (5.000E-04*jval_NO2)
  RCONST(260) = (5.000E-04*jval_NO2)
  RCONST(261) = (5.000E-04*jval_NO2)
  RCONST(262) = (5.000E-04*jval_NO2)
  RCONST(263) = (5.000E-04*jval_NO2)
  RCONST(264) = (5.000E-04*jval_NO2)
  RCONST(265) = (5.000E-04*jval_NO2)
  RCONST(266) = (5.000E-04*jval_NO2)
  RCONST(267) = (5.000E-04*jval_NO2)
  RCONST(268) = (5.000E-04*jval_NO2)
  RCONST(269) = (5.000E-04*jval_NO2)
  RCONST(270) = (5.000E-04*jval_NO2)
  RCONST(271) = (5.000E-04*jval_NO2)
  RCONST(272) = (4.590E-04*jval_NO2)
  RCONST(273) = (5.000E-04*jval_NO2)
  RCONST(368) = (5.000E-03*jval_NO2)
  RCONST(369) = (3.000E-02*jval_NO2)
  RCONST(370) = (3.000E-02*jval_NO2)
  RCONST(429) = (1.000E-03*jval_NO2)
  RCONST(430) = (1.000E-03*jval_NO2)
  RCONST(431) = (1.000E-03*jval_NO2)
  RCONST(432) = (1.000E-03*jval_NO2)
  RCONST(433) = (1.000E-03*jval_NO2)
  RCONST(435) = (5.000E-04*jval_NO2)
  RCONST(436) = (5.000E-04*jval_NO2)
  RCONST(437) = (5.000E-04*jval_NO2)
  RCONST(442) = (5.000E-04*jval_NO2)
  RCONST(443) = (5.000E-04*jval_NO2)
      
END SUBROUTINE Update_PHOTO

! End of Update_PHOTO function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE gasphs_Rates

