! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! The Reaction Rates File
!
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
!
! File                 : mod_cbmz_Rates.f90
! Time                 : Mon Nov 25 13:41:15 2013
! Working directory    : /scratch/ashalaby/kpp-2.2.3/compare/CBMZ
! Equation file        : mod_cbmz.kpp
! Output root filename : mod_cbmz
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE mod_cbmz_Rates

  USE mod_cbmz_Parameters
  USE mod_cbmz_Global
  IMPLICIT NONE

CONTAINS



! Begin Rate Law Functions from KPP_HOME/util/UserRateLaws

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  User-defined Rate Law functions
!  Note: the default argument type for rate laws, as read from the equations file, is single precision
!        but all the internal calculations are performed in double precision
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!~~~>  Arrhenius
   REAL(kind=dp) FUNCTION ARR( A0,B0,C0 )
      REAL A0,B0,C0
      ARR =  DBLE(A0) * EXP(-DBLE(B0)/TEMP) * (TEMP/300.0_dp)**DBLE(C0)
   END FUNCTION ARR

!~~~> Simplified Arrhenius, with two arguments
!~~~> Note: The argument B0 has a changed sign when compared to ARR
   REAL(kind=dp) FUNCTION ARR2( A0,B0 )
      REAL A0,B0
      ARR2 =  DBLE(A0) * EXP( DBLE(B0)/TEMP )
   END FUNCTION ARR2
!~~~~~~~~~~~~~~>     added by A. shalaby June 2007 --------------------
   REAL(kind=dp) FUNCTION ARR3FC( A0,B0,A1,B1,FC )
      REAL A0,B0,A1,B1,FC
      REAL(kind=dp) k1,k2,ex
      K1=A0*(300/TEMP)**B0
      k2=A1*(300/TEMP)**B1
      ex=(1+(log10(k1*C_M/k2))**2)**(-1)
      ARR3FC = (K1*C_M/(1+(K1*C_M/K2)))*FC**(ex)
   END FUNCTION ARR3FC
!----------------------------------------------------------------------
!~~~~~~~~~~~~~~>     added by A. shalaby June 2007 --------------------
   REAL(kind=dp) FUNCTION ARR4( A0,B0,C0,A1,B1,C1,FC )
      REAL A0,B0,C0,A1,B1,C1,FC
      REAL(kind=dp) k1,k2,ex
      K1=A0*((300/TEMP)**B0)*EXP(C0/TEMP)
      k2=A1*((300/TEMP)**B1)*EXP(C1/TEMP)
      ex=(1+(log(k1*C_M/k2))**2)**(-1)
      ARR4 = (k2*k1*C_M)/(k2+k1*C_M)*FC**(ex)
   END FUNCTION ARR4
!----------------------------------------------------------------------

   REAL(kind=dp) FUNCTION EP2(A0,C0,A2,C2,A3,C3)
      REAL A0,C0,A2,C2,A3,C3
      REAL(kind=dp) K0,K2,K3
      K0 = DBLE(A0) * EXP(-DBLE(C0)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      K3 = DBLE(A3) * EXP(-DBLE(C3)/TEMP)
      K3 = K3*CFACTOR*1.0E6_dp
      EP2 = K0 + K3/(1.0_dp+K3/K2 )
   END FUNCTION EP2

   REAL(kind=dp) FUNCTION EP3(A1,C1,A2,C2)
      REAL A1, C1, A2, C2
      REAL(kind=dp) K1, K2
      K1 = DBLE(A1) * EXP(-DBLE(C1)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      EP3 = K1 + K2*(1.0E6_dp*CFACTOR)
   END FUNCTION EP3

   REAL(kind=dp) FUNCTION FALL ( A0,B0,C0,A1,B1,C1,CF)
      REAL A0,B0,C0,A1,B1,C1,CF
      REAL(kind=dp) K0, K1
      K0 = DBLE(A0) * EXP(-DBLE(B0)/TEMP)* (TEMP/300.0_dp)**DBLE(C0)
      K1 = DBLE(A1) * EXP(-DBLE(B1)/TEMP)* (TEMP/300.0_dp)**DBLE(C1)
      K0 = K0*CFACTOR*1.0E6_dp
      K1 = K0/K1
      FALL = (K0/(1.0_dp+K1))*   &
           DBLE(CF)**(1.0_dp/(1.0_dp+(LOG10(K1))**2))
   END FUNCTION FALL

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_3rd(temp,cair,k0_300K,n,kinf_300K,m,fc)

    INTRINSIC LOG10

    REAL(kind=dp), INTENT(IN) :: temp      ! temperature [K]
    REAL(kind=dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL, INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL, INTENT(IN) :: n         ! exponent for low pressure limit
    REAL, INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL, INTENT(IN) :: m         ! exponent for high pressure limit
    REAL, INTENT(IN) :: fc        ! broadening factor (usually fc=0.6)
    REAL(kind=dp) :: zt_help, k0_T, kinf_T, k_ratio

    zt_help = 300._dp/temp
    k0_T    = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    k_3rd   = k0_T/(1._dp+k_ratio)*fc**(1._dp/(1._dp+LOG10(k_ratio)**2))

  END FUNCTION k_3rd

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_arr (k_298,tdep,temp)
    ! Arrhenius function

    REAL,     INTENT(IN) :: k_298 ! k at T = 298.15K
    REAL,     INTENT(IN) :: tdep  ! temperature dependence
    REAL(kind=dp), INTENT(IN) :: temp  ! temperature

    INTRINSIC EXP

    k_arr = k_298 * EXP(tdep*(1._dp/temp-3.3540E-3_dp)) ! 1/298.15=3.3540e-3

  END FUNCTION k_arr

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  End of User-defined Rate Law functions
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! End Rate Law Functions from KPP_HOME/util/UserRateLaws


! Begin INLINED Rate Law Functions


   REAL(KIND=dp) FUNCTION ARR3( A0,B0,A1,B1)
      REAL A0,B0,A1,B1
      REAL(KIND=dp) k1,k2,ex

      K1=A0*C_M*(300/TEMP)**(B0)
      k2=A1*(300/TEMP)**(B1)
      ex=1./(1+(log(k1/k2))**2)
      ARR3 = (k2*k1*C_M)/(k2+k1*C_M)*0.6**(ex)
   END FUNCTION ARR3

REAL(KIND=dp) FUNCTION CBZ1( TEMP, C_M )
    REAL(KIND=dp), INTENT(IN) :: TEMP, C_M
    REAL(KIND=dp) :: ka, kb, kc

   ka  = 7.2E-15_dp * EXP(785._dp/TEMP)
   kb  = 1.9E-33_dp * EXP(725._dp/TEMP)
   kc  = 4.1E-16_dp * EXP(1440._dp/TEMP)
   CBZ1 = (ka+C_M*kb)/(1+(C_M*kb/kc))
END FUNCTION CBZ1

REAL(KIND=dp) FUNCTION CBZ2( TEMP, C_M )
    REAL(KIND=dp), INTENT(IN) :: TEMP, C_M
    REAL(KIND=dp) :: kd, ke
    kd = 2.3E-13*EXP(600./TEMP)
    ke = 1.7E-33*EXP(1000./TEMP)
    CBZ2 = kd + C_M*ke
END FUNCTION CBZ2
SUBROUTINE loadperoxyparameters
implicit none
 integer i, j
Aperox(jch3o2,jch3o2)   = 2.5e-13
Aperox(jethp,jethp)     = 6.8e-14
Aperox(jc2o3,jc2o3)     = 2.9e-12
Aperox(jano2,jano2)     = 8.0e-12
Aperox(jnap,jnap)       = 1.0e-12
Aperox(jro2,jro2)       = 5.3e-16
Aperox(jisopp,jisopp)   = 3.1e-14
Aperox(jisopn,jisopn)   = 3.1e-14
Aperox(jisopo2,jisopo2) = 3.1e-14
Aperox(jxo2,jxo2)       = 3.1e-14

Bperox(jch3o2,jch3o2)   = 190.
Bperox(jethp,jethp)     = 0.0
Bperox(jc2o3,jc2o3)     = 500.
Bperox(jano2,jano2)     = 0.0
Bperox(jnap,jnap)       = 0.0
Bperox(jro2,jro2)       = 1980.
Bperox(jisopp,jisopp)   = 1000.
Bperox(jisopn,jisopn)   = 1000.
Bperox(jisopo2,jisopo2) = 1000.
Bperox(jxo2,jxo2)       = 1000.

do i = 1, nperox
do j = 1, nperox
if(i.ne.j)then
Aperox(i,j) = 2.0*sqrt(Aperox(i,i)*Aperox(j,j))
Bperox(i,j) = 0.5*(Bperox(i,i) + Bperox(j,j))
end if
end do
end do
Aperox(jc2o3,jch3o2) = 1.3e-12
Aperox(jch3o2,jc2o3) = 1.3e-12
return
END SUBROUTINE loadperoxyparameters

SUBROUTINE peroxyrateconstants

implicit none
integer i, j
real(kind=dp) sperox(nperox), rk_perox(nperox,nperox)
sperox(jch3o2)  =  VAR(indv_CH3O2)!C_CH3O2
sperox(jethp)   =  VAR(indv_ETHP) ! C_ETHP
sperox(jro2)    =  VAR(indv_RO2)  ! C_RO2
sperox(jc2o3)   =  VAR(indv_C2O3) ! C_C2O3
sperox(jano2)   =  VAR(indv_ANO2) ! C_ANO2
sperox(jnap)    =  VAR(indv_NAP)  ! C_NAP
sperox(jisopp)  =  VAR(indv_ISOPP)! C_ISOPP
sperox(jisopn)  =  VAR(indv_ISOPN)! C_ISOPN
sperox(jisopo2) =  VAR(indv_ISOPO2)! C_ISOPO2
sperox(jxo2)    =  VAR(indv_XO2)  ! C_XO2

do i = 1, nperox
rk_param(i) = 0.0
end do

do i = 1, nperox
do j = 1, nperox
rk_perox(i,j) = ARR2( Aperox(i,j), Bperox(i,j))
rk_param(i) = rk_param(i) + real(rk_perox(i,j)*sperox(j))
end do
end do

return
END SUBROUTINE peroxyrateconstants
REAL(KIND=dp) FUNCTION react(k)
 INTEGER :: k
! CALL loadperoxyparameters
 CALL peroxyrateconstants
 react=rk_param(k)

END FUNCTION react
REAL(KIND=dp) FUNCTION KDMS( TEMP)
    REAL(KIND=dp), INTENT(IN) :: TEMP
    REAL(KIND=dp) :: k0, k1, k2,k3,k4

   k0=TEMP*EXP(-234/TEMP)
   k1=8.46E-10*EXP(7230/TEMP)
   k2=2.68E-10*EXP(7810/TEMP)
   k3=1.04E11*TEMP
   k4=88.1*EXP(7460/TEMP)

   KDMS=(k0+k1+k2)/(k3+k4)


END FUNCTION KDMS






! End INLINED Rate Law Functions

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! Update_SUN - update SUN light using TIME
!   Arguments :
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  SUBROUTINE Update_SUN()
      !USE mod_cbmz_Parameters
      !USE mod_cbmz_Global

    IMPLICIT NONE

    REAL(kind=dp) :: SunRise, SunSet
    REAL(kind=dp) :: Thour, Tlocal, Ttmp
    ! PI - Value of pi
    REAL(kind=dp), PARAMETER :: PI = 3.14159265358979d0

    SunRise = 4.5_dp
    SunSet  = 19.5_dp
    Thour = TIME/3600.0_dp
    Tlocal = Thour - (INT(Thour)/24)*24

    IF ((Tlocal>=SunRise).AND.(Tlocal<=SunSet)) THEN
       Ttmp = (2.0*Tlocal-SunRise-SunSet)/(SunSet-SunRise)
       IF (Ttmp.GT.0) THEN
          Ttmp =  Ttmp*Ttmp
       ELSE
          Ttmp = -Ttmp*Ttmp
       END IF
       SUN = ( 1.0_dp + COS(PI*Ttmp) )/2.0_dp
    ELSE
       SUN = 0.0_dp
    END IF

 END SUBROUTINE Update_SUN

! End of Update_SUN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! Update_RCONST - function to update rate constants
!   Arguments :
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_RCONST ( )




! Begin INLINED RCONST


! End INLINED RCONST

  RCONST(1) = (jval_NO2)
  RCONST(2) = (jval_NO3a)
  RCONST(3) = (jval_HNO2)
  RCONST(4) = (jval_HNO3)
  RCONST(5) = (jval_HNO4)
  RCONST(6) = (jval_O33P)
  RCONST(7) = (jval_O31D)
  RCONST(8) = (jval_H2O2)
  RCONST(9) = (ARR2(3.2E-11,70.))
  RCONST(10) = (ARR2(1.8E-11,110.0))
! RCONST(11) = constant rate coefficient
  RCONST(12) = (C_M*6.0E-34*((TEMP/300)**(-2.3)))
  RCONST(13) = (ARR2(8.0E-12,-2060.))
  RCONST(14) = (ARR2(6.5E-12,-120.0))
  RCONST(15) = (ARR3(9.0E-32,2.0,2.2E-11,0.))
  RCONST(16) = (ARR3(9.0E-32,1.5,3.0E-11,0.0))
  RCONST(17) = (ARR2(2.0E-12,-1400.))
  RCONST(18) = (ARR2(1.2E-13,-2450.0))
  RCONST(19) = (ARR2(1.6E-12,-940.0))
  RCONST(20) = (ARR2(1.1E-14,-500.0))
  RCONST(21) = (ARR2(5.5E-12,-2000.))
  RCONST(22) = (ARR3(7.0E-31,2.6,3.6E-11,0.1))
  RCONST(23) = (ARR3(2.5E-30,4.4,1.6E-11,1.7))
! RCONST(24) = constant rate coefficient
  RCONST(25) = (ARR2(1.8E-11,-390.))
  RCONST(26) = (CBZ1(TEMP,C_M))
  RCONST(27) = (ARR2(1.3E-12,380.0))
  RCONST(28) = (ARR2(4.8E-11,250.0))
  RCONST(29) = (ARR2(2.9E-12,-160.0))
  RCONST(30) = (CBZ2(TEMP,C_M))
  RCONST(31) = (CBZ2(TEMP,C_M)*ARR2(1.4E-21,2200.))
  RCONST(32) = (ARR2(3.5E-12,250.0))
  RCONST(33) = (ARR3(1.8E-31,3.2,4.7E-12,1.4))
! RCONST(34) = constant rate coefficient
  RCONST(35) = (ARR3(1.8E-31,3.2,4.7E-12,1.4)*ARR2(4.76E26,-10900.))
  RCONST(36) = (ARR2(1.5E-11,170.0))
  RCONST(37) = (ARR2(4.5E-14,-1260.0))
  RCONST(38) = (ARR3(2.2E-30,3.9,1.5E-12,0.7))
  RCONST(39) = (ARR2(8.5E-13,-2450.))
! RCONST(40) = constant rate coefficient
! RCONST(41) = constant rate coefficient
  RCONST(42) = (ARR3(2.2E-30,3.9,1.5E-12,0.7)*ARR2(3.7E26,-11000.))
  RCONST(43) = (ARR2(3.3E-39,530.0))
  RCONST(44) = (1.5E-13*(1.+2.439E-20*C_M))
  RCONST(45) = (ARR3(3.0E-31,3.3,1.5E-12,0.0))
  RCONST(46) = ((TEMP**0.667)*ARR2(2.8E-14,-1575.))
  RCONST(47) = ((TEMP**2)*ARR2(1.5E-17,-492.))
! RCONST(48) = constant rate coefficient
  RCONST(49) = (ARR2(6.7E-12,-600.))
  RCONST(50) = (jval_CH2Oa)
  RCONST(51) = (jval_CH2Ob)
! RCONST(52) = constant rate coefficient
  RCONST(53) = (ARR2(3.4E-13,-1900.))
  RCONST(54) = (jval_CH3CHOa)
  RCONST(55) = (ARR2(5.6E-12,270.))
  RCONST(56) = (ARR2(1.4E-12,-1900.))
  RCONST(57) = (jval_CH3COCH3)
  RCONST(58) = ((TEMP**2)*ARR2(5.3E-18,-230.))
  RCONST(59) = (9.64*jval_CH2Oa)
! RCONST(60) = constant rate coefficient
  RCONST(61) = (ARR2(1.4E-12,-1900.))
  RCONST(62) = (ARR2(1.2E-14,-2630.))
  RCONST(63) = (ARR3(1.0E-28,0.8,8.8E-12,0.0))
  RCONST(64) = (ARR2(4.2E-15,-1800.))
  RCONST(65) = (ARR2(8.9E-16,-392.))
  RCONST(66) = (ARR2(5.8E-12,478.))
  RCONST(67) = (ARR2(2.9E-11,255.))
  RCONST(68) = (ARR2(3.1E-13,-1010.))
! RCONST(69) = constant rate coefficient
  RCONST(70) = (ARR2(2.1E-12,322.))
  RCONST(71) = (ARR2(1.7E-11,116.))
! RCONST(72) = constant rate coefficient
! RCONST(73) = constant rate coefficient
! RCONST(74) = constant rate coefficient
! RCONST(75) = constant rate coefficient
! RCONST(76) = constant rate coefficient
  RCONST(77) = (9.04*jval_CH2Oa)
  RCONST(78) = (ARR2(5.4E-17,-500.))
  RCONST(79) = (ARR2(2.55E-11,409.))
  RCONST(80) = (ARR2(1.2E-14,-2013.))
  RCONST(81) = (ARR2(3.0E-12,-446.))
! RCONST(82) = constant rate coefficient
! RCONST(83) = constant rate coefficient
  RCONST(84) = (5.000E-04*jval_NO2)
! RCONST(85) = constant rate coefficient
  RCONST(86) = (jval_CH3OOH)
  RCONST(87) = (jval_CH3OOH)
  RCONST(88) = (jval_CH3OOH)
  RCONST(89) = (ARR2(3.8E-12,200.))
  RCONST(90) = (ARR2(3.8E-12,200.))
  RCONST(91) = (ARR2(3.8E-12,200.))
  RCONST(92) = (ARR2(1.6E-11,-540.))
  RCONST(93) = (5.000E-04*jval_NO2)
  RCONST(94) = (ARR3(9.7E-29,5.6,9.3E-12,1.5))
  RCONST(95) = (ARR3(9.7E-29,5.6,9.3E-12,1.5)*ARR2(1.1E28,-14000.))
  RCONST(96) = (ARR2(3.E-12,280.))
  RCONST(97) = (ARR2(2.6E-12,365.))
! RCONST(98) = constant rate coefficient
  RCONST(99) = (ARR2(5.3E-12,360.))
! RCONST(100) = constant rate coefficient
! RCONST(101) = constant rate coefficient
! RCONST(102) = constant rate coefficient
! RCONST(103) = constant rate coefficient
! RCONST(104) = constant rate coefficient
! RCONST(105) = constant rate coefficient
! RCONST(106) = constant rate coefficient
! RCONST(107) = constant rate coefficient
! RCONST(108) = constant rate coefficient
! RCONST(109) = constant rate coefficient
! RCONST(110) = constant rate coefficient
! RCONST(111) = constant rate coefficient
! RCONST(112) = constant rate coefficient
  RCONST(113) = (ARR2(3.8E-13,800.))
  RCONST(114) = (ARR2(7.5E-13,700.))
  RCONST(115) = (ARR2(1.7E-13,1300.))
  RCONST(116) = (ARR2(4.5E-13,1000.))
  RCONST(117) = (ARR2(1.2E-13,1300.))
  RCONST(118) = (ARR2(1.7E-13,1300.))
  RCONST(119) = (ARR2(1.7E-13,1300.))
  RCONST(120) = (ARR2(1.7E-13,1300.))
  RCONST(121) = (ARR2(1.7E-13,1300.))
  RCONST(122) = (ARR2(1.7E-13,1300.))
  RCONST(123) = (KDMS(TEMP))
  RCONST(124) = (ARR2(1.0E-12,500.))

END SUBROUTINE Update_RCONST

! End of Update_RCONST function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! Update_PHOTO - function to update photolytical rate constants
!   Arguments :
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_PHOTO ( )


   USE mod_cbmz_Global

  RCONST(1) = (jval_NO2)
  RCONST(2) = (jval_NO3a)
  RCONST(3) = (jval_HNO2)
  RCONST(4) = (jval_HNO3)
  RCONST(5) = (jval_HNO4)
  RCONST(6) = (jval_O33P)
  RCONST(7) = (jval_O31D)
  RCONST(8) = (jval_H2O2)
  RCONST(50) = (jval_CH2Oa)
  RCONST(51) = (jval_CH2Ob)
  RCONST(54) = (jval_CH3CHOa)
  RCONST(57) = (jval_CH3COCH3)
  RCONST(59) = (9.64*jval_CH2Oa)
  RCONST(77) = (9.04*jval_CH2Oa)
  RCONST(84) = (5.000E-04*jval_NO2)
  RCONST(86) = (jval_CH3OOH)
  RCONST(87) = (jval_CH3OOH)
  RCONST(88) = (jval_CH3OOH)
  RCONST(93) = (5.000E-04*jval_NO2)

END SUBROUTINE Update_PHOTO

! End of Update_PHOTO function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE mod_cbmz_Rates

! vim: tabstop=8 expandtab shiftwidth=2 softtabstop=2
