! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! Main Program File
!
! Generated by KPP-2.2 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
!
! File                 : gasphs_Main.f90
! Time                 : Wed Aug 20 11:07:49 2008
! Working directory    : /scratch/ASHALABY/KPP/COMPARE_DMS/lsode_CBMZ
! Equation file        : gasphs.kpp
! Output root filename : gasphs
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! MAIN - Main program - driver routine
!   Arguments :
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
module mod_cbmz_main1
  use mod_cbmz_Model
  use mod_cbmz_Global
  use mod_cbmz_Parameters

  public :: chemmain

  contains

  subroutine chemmain(jday,dtche)
    use mod_cbmz_Model
    use mod_cbmz_Global
    use mod_cbmz_Parameters
    use mod_cbmz_jval1
    implicit none

    real(kind=dp) , intent(in) :: jday , dtche

    real(kind=dp) :: t
    real(kind=dp) :: rstate(20)
    integer :: i

    !------------------Declaration part for jval----------

    integer :: c_hvin
    integer , dimension(22) :: c_nhv(22)
    real(kind=dp) , dimension(22) :: jparam
    real(kind=dp) , dimension(22,40) :: c_hvmat
    real(kind=dp) , dimension(22) :: c_hvmatb
    real(kind=dp) , dimension(80,510,56) :: c_jarray

    common /hvrvars/ c_hvmat , c_hvmatb , c_jarray
    common /HVINT/ c_hvin , c_nhv
    real(kind=dp) , dimension(56) :: jval

    integer , parameter :: jO2       = 1
    integer , parameter :: jO31D     = 2
    integer , parameter :: jO33P     = 3
    integer , parameter :: jNO2      = 4
    integer , parameter :: jNO3a     = 5
    integer , parameter :: jNO3b     = 6
    integer , parameter :: jN2O5a    = 7
    integer , parameter :: jN2O5b    = 8
    integer , parameter :: jN2O      = 9
    integer , parameter :: jHO2      = 10
    integer , parameter :: jH2O2     = 11
    integer , parameter :: jHNO2     = 12
    integer , parameter :: jHNO3     = 13
    integer , parameter :: jHNO4     = 14
    integer , parameter :: jCH2Oa    = 15
    integer , parameter :: jCH2Ob    = 16
    integer , parameter :: jCH3CHOa  = 17
    integer , parameter :: jCH3CHOb  = 18
    integer , parameter :: jCH3CHOc  = 19
    integer , parameter :: jC2H5CHO  = 20
    integer , parameter :: jCHOCHO   = 21
    integer , parameter :: jCH3COCHO = 22
    integer , parameter :: jCH3COCH3 = 23
    integer , parameter :: jCH3OOH   = 24
    integer , parameter :: jCH3ONO2  = 25
    integer , parameter :: jPAN      = 26

    !~~~> Initialization

    var => c(1:nvar)
    fix => c(nvar+1:)

    stepmin = 0.0d0
    stepmax = 0.0d0

    do i = 1 , nvar
      rtol(i) = 0.1D0
      atol(i) = 0.1D0
    end do
    fix(1) = (0.22D0)*C_M
    fix(2) = (0.78D0)*C_M

    call loadperoxyparameters

    ! constant rate coefficients
    rconst(11) = 2.2D-10
    rconst(24) = 2.2D-11
    rconst(34) = 5D-16
    rconst(40) = 3.5D-12
    rconst(41) = 2D-21
    rconst(48) = 8.1D-13
    rconst(52) = 1D-11
    rconst(60) = 1.7D-11
    rconst(69) = 2.5D-12
    rconst(72) = 8.1D-12
    rconst(73) = 4.1D-11
    rconst(74) = 2.2D-11
    rconst(75) = 1.4D-11
    rconst(76) = 3D-11
    rconst(82) = 3.3D-11
    rconst(83) = 7D-18
    rconst(85) = 1D-15
    rconst(98) = 4D-12
    rconst(100) = 4D-12
    rconst(101) = 4D-12
    rconst(102) = 4D-12
    rconst(103) = 4D-12
    rconst(104) = 4D-12
    rconst(105) = 4D-12
    rconst(106) = 1.1D-12
    rconst(107) = 2.5D-12
    rconst(108) = 2.5D-12
    rconst(109) = 4D-12
    rconst(110) = 1.2D-12
    rconst(111) = 4D-12
    rconst(112) = 2.5D-12

    tstart = 0.0D0*3600.0D0
    dt = dtche

    do i = 1 , nvar
      var(i)  = xrin(i)
    end do
    t = tstart
    tend = tstart+dtche

    time = t
    jparam(1) = zenith
    jparam(2) = altmid
    jparam(3) = 330._dp
    jparam(4) = 0.1_dp
    jparam(5) = 0.1_dp
    jparam(6) = 0.38_dp
    jparam(7) = 0.85_dp
    jparam(8) = 0.1_dp
    jparam(9) = deptha
    jparam(10)= depthb
    jparam(11)= altabove
    jparam(12)= altbelow
    jparam(13)= temp
    jparam(20)= jday

    call jvalpro(c_nhv,c_hvmat,c_jarray,jparam,jval)

    jval_O31D     =  jval(jO31D)
    jval_O33P     =  jval(jO33P)
    jval_NO2      =  jval(jNO2)
    jval_H2O2     =  jval(jH2O2)
    jval_CH2Oa    =  jval(jCH2Oa)
    jval_CH2Ob    =  jval(jCH2Ob)
    jval_HNO3     =  jval(jHNO3)
    jval_HNO2     =  jval(jHNO2)
    jval_HNO4     =  jval(jHNO4)
    jval_NO3b     =  jval(jNO3b)
    jval_NO3a     =  jval(jNO3a)
    jval_N2O5b    =  jval(jN2O5b)
    jval_CH3CHOa  =  jval(jCH3CHOa)
    jval_PAN      =  jval(jPAN)
    jval_C2H5CHO  =  jval(jC2H5CHO)
    jval_CH3COCH3 =  jval(jCH3COCH3)
    jval_CHOCHO   =  jval(jCHOCHO)
    c_jval(1,:)   = jval(:)

    kron: &
    do while (t < tend)
      call update_rconst()
      call integrate( tin = t, tout = t+dt, rstatus_u = rstate, &
               icntrl_u = (/ 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 /))
      t = rstate(1)
    end do kron

    do i = 1 , nvar
      xrout(i) = var(i)
    end do

  end subroutine chemmain

end module  mod_cbmz_main1

! vim: tabstop=8 expandtab shiftwidth=2 softtabstop=2
