! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! Main Program File
!
! Generated by KPP-2.2 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
!
! File                 : gasphs_Main.f90
! Time                 : Wed Aug 20 11:07:49 2008
! Working directory    : /scratch/ASHALABY/KPP/COMPARE_DMS/lsode_CBMZ
! Equation file        : gasphs.kpp
! Output root filename : gasphs
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! MAIN - Main program - driver routine
!   Arguments :
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
module mod_cbmz_main1
  USE mod_cbmz_Model
  USE mod_cbmz_Global
  USE mod_cbmz_Parameters
public :: chemmain
contains
  subroutine chemmain
  USE mod_cbmz_Model
  USE mod_cbmz_Model
  USE mod_cbmz_Global
  USE mod_cbmz_Parameters
  USE mod_cbmz_jval1
  implicit none


      REAL(kind=dp) :: T, TT,DVAL(NSPEC)
      REAL(kind=dp) :: RSTATE(20)
      INTEGER :: i
! LOCAL VARIABLES

      INTEGER IMN(12)                                                   &
                     ,IIYEAR, IYEAR, IMTH, IDAY, IIY
      DATA IMN/31,28,31,30,31,30,31,31,30,31,30,31/

!------------------Declaration part for jval----------
      integer c_hvin
      integer c_nhv(22)
      REAL(kind=dp) jparam(       22)
      REAL(kind=dp) c_hvmat(22,40)
      REAL(kind=dp) c_hvmatb(22)
      REAL(kind=dp) c_jarray(80,510,56)
      common/HVRVARS/c_hvmat, c_hvmatb, c_jarray
      common/HVINT/ c_hvin,c_nhv
      REAL(kind=dp)  jval(       56)

      INTEGER, PARAMETER :: jO2=1,jO31D=2,jO33P=3,jNO2=4,jNO3a=5 &
           ,jNO3b=6,jN2O5a=7,jN2O5b=8,jN2O=9,jHO2=10             &
           ,jH2O2=11,jHNO2=12,jHNO3=13,jHNO4=14,jCH2Oa=15        &
           ,jCH2Ob=16,jCH3CHOa=17,jCH3CHOb=18,jCH3CHOc=19        &
           ,jC2H5CHO=20,jCHOCHO=21,jCH3COCHO=22                  &
           ,jCH3COCH3=23,jCH3OOH=24,jCH3ONO2=25,jPAN=26
!--------------Reading TUVGRID2 part in jval--------------
!~~~> Initialization

      STEPMIN = 0.0d0
      STEPMAX = 0.0d0

      DO i=1,NVAR
        RTOL(i) =1.0d-1
        ATOL(i) =1.0d-1
      END DO
  FIX(1) = (0.22)*C_M
  FIX(2) = (0.78)*C_M

      CALL loadperoxyparameters
! constant rate coefficients
  RCONST(11) = 2.2e-10
  RCONST(24) = 2.2e-11
  RCONST(34) = 5e-16
  RCONST(40) = 3.5e-12
  RCONST(41) = 2e-21
  RCONST(48) = 8.1e-13
  RCONST(52) = 1e-11
  RCONST(60) = 1.7e-11
  RCONST(69) = 2.5e-12
  RCONST(72) = 8.1e-12
  RCONST(73) = 4.1e-11
  RCONST(74) = 2.2e-11
  RCONST(75) = 1.4e-11
  RCONST(76) = 3e-11
  RCONST(82) = 3.3e-11
  RCONST(83) = 7e-18
  RCONST(85) = 1e-15
  RCONST(98) = 4e-12
  RCONST(100) = 4e-12
  RCONST(101) = 4e-12
  RCONST(102) = 4e-12
  RCONST(103) = 4e-12
  RCONST(104) = 4e-12
  RCONST(105) = 4e-12
  RCONST(106) = 1.1e-12
  RCONST(107) = 2.5e-12
  RCONST(108) = 2.5e-12
  RCONST(109) = 4e-12
  RCONST(110) = 1.2e-12
  RCONST(111) = 4e-12
  RCONST(112) = 2.5e-12
! END constant rate coefficients

      TSTART = 0.0*3600
      DT = 900.0


      DO i=1,NVAR
      VAR(i)  = xrin(i)
      END DO
      T = TSTART
      TEND = TSTART+(DT)

      TIME = T
      jparam(1) = zenith
      jparam(2) = altmid
      jparam(3) = 330._dp
      jparam(4) = 0.1_dp
      jparam(5) = 0.1_dp
      jparam(6) = 0.38_dp
      jparam(7) = 0.85_dp
      jparam(8) = 0.1_dp
      jparam(9) = deptha
      jparam(10)= depthb
      jparam(11)= altabove
      jparam(12)= altbelow
      jparam(13)= TEMP
      TEMP      = TEMP

      CALL jvalpro(c_nhv,c_hvmat,c_jarray,jparam, jval)
        jval_O31D    =  jval(jO31D)
        jval_O33P    =  jval(jO33P)
        jval_NO2     =  jval(jNO2)
        jval_H2O2    =  jval(jH2O2)
        jval_CH2Oa   =  jval(jCH2Oa)
        jval_CH2Ob   =  jval(jCH2Ob)
        jval_HNO3    =  jval(jHNO3)
        jval_HNO2    =  jval(jHNO2)
        jval_HNO4    =  jval(jHNO4)
        jval_NO3b    =  jval(jNO3b)
        jval_NO3a    =  jval(jNO3a)
        jval_N2O5b   =  jval(jN2O5b)
        jval_CH3CHOa =  jval(jCH3CHOa)
        jval_PAN     =  jval(jPAN)
        jval_C2H5CHO =  jval(jC2H5CHO)
        jval_CH3COCH3=  jval(jCH3COCH3)
        jval_CHOCHO  =  jval(jCHOCHO)
        c_jval(1,:)       = jval(:)



kron: DO WHILE (T < TEND)

        CALL Update_RCONST()

        CALL INTEGRATE( TIN = T, TOUT = T+DT, RSTATUS_U = RSTATE, &
        ICNTRL_U = (/ 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 /))

        T = RSTATE(1)

      END DO kron
!~~~> End Time loop
      DO i=1,NVAR
      xrout(i) = VAR(i)
      END DO


     end subroutine chemmain

end module  mod_cbmz_main1
! End of MAIN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! vim: tabstop=8 expandtab shiftwidth=2 softtabstop=2
