#!/usr/bin/python
# Script that evaluates differences between different
# initial conditions for RegCM v3-v4 and produces
# png images of the GrADS plots

import os,sys,subprocess

check_domain="""* Script generated by preproc-compare.py
'open PATH1/DOMAIN.CTL'
'open PATH2/DOMAIN.CTL'
'htdm=abs(ht.1-ht.2)'
'd htdm'
'printim elev.png'
"""

check_icbc="""* Script generated by preproc-compare.py
'open PATH1/ICBC1994010100.CTL'
'open PATH2/ICBC1994010100.CTL'
'tdm=ave(abs(t.1-t.2),T=1,T=125)'
'd tdm'
'printim temp.png'
'clear'
'wdm=ave(abs(sqrt(u.1*u.1+v.1*v.1)-sqrt(u.2*u.2+v.2*v.2)),T=1,T=125)'
'd wdm'
'printim windmag.png'
'clear'
'qdm=ave(abs(q.1-q.2),T=1,T=125)'
'd qdm'
'printim moist.png'
'clear'
'pxdm=ave(abs(px.1-px.2),T=1,T=125)'
'd pxdm'
'printim press.png'
'clear'
'tsdm=ave(abs(ts.1-ts.2),T=1,T=125)'
'd tsdm'
'printim satemp.png'"""

path1=raw_input("Please enter 1st path : ")
if os.path.isdir(path1):
    print "Files read from ",path1
else :
    print path1,"is not a valid path"
    sys.exit(1)


path2=raw_input("Please enter 2nd path : ")
if os.path.isdir(path2):
    print "Files read from ",path2
else :
    print path2,"is not a valid path"
    sys.exit(1)

check_domain = check_domain.replace("PATH1",path1)
check_domain = check_domain.replace("PATH2",path2)

check_icbc = check_icbc.replace("PATH1",path1)
check_icbc = check_icbc.replace("PATH2",path2)

out1 = open("check-domain.gs","w")
out1.write(check_domain)

out2 = open("check-icbc.gs","w")
out2.write(check_icbc)

out1.close()
out2.close()

subprocess.call(["gradsc","-lbxc","check-domain.gs"])
subprocess.call(["gradsc","-lbxc","check-icbc.gs"])

os.remove("check-domain.gs")
os.remove("check-icbc.gs")
