format: cordex
cache: /leonardo_scratch/large/userexternal/ggiulian/cache
datapath: /leonardo/home/userexternal/ggiulian/project/COUPLED/atmonly/CORDEX-CMIP6
plotpath: /leonardo_scratch/large/userexternal/ggiulian/plots
plot:
        biasplot:
                years: [1979:1987]
                name: MED-12 standalone
                dpi: 100
                seasons: [ "DJF", "MAM", "JJA", "SON" ]
                variables:
                        tas:
                                obs: [ "EOBS", "CRU", "ERA5" ]
                        pr:
                                obs: [ "EOBS", "CRU", "ERA5", "MSWEP", "CPC" ]
                        clt:
                                obs: [ "CRU", "ERA5" ]
