all:
	@echo "Usage: make ifc11  where ifc11 is the target machine "
	@echo "for a complete list of target: make list "

clean:
	rm -f regcm *.o

ifc11:
	make -f Makefile_IFC11
ifc8:
	make -f Makefile_IFC8
pgi:
	make -f Makefile_PGI
gnu:
	make -f Makefile_gnu
#Makefile_AMD64p_IFC8
#Makefile_CL2
#Makefile_DEC
#Makefile_IBM
#Makefile_IFC7
#Makefile_IFC8
#Makefile_PGI
#Makefile_SGI
#Makefile_SISSA_IFC8
#Makefile_SP2p
#Makefile_SUN
