! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : cb6_Parameters.f90
! Time                 : Mon Nov 24 11:54:36 2014
! Working directory    : /home/regcm/Code/kpp-2.2.3/Workspace/GAS_CB6r2
! Equation file        : cb6.kpp
! Output root filename : cb6
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE mod_cb6_Parameters

  USE mod_cb6_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 82 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 76 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 74 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 6 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 215 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 77 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 921 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 1061 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 77 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 11 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 7 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_NTR = 1 
  INTEGER, PARAMETER :: ind_SULF = 2 
  INTEGER, PARAMETER :: ind_SO2 = 3 
  INTEGER, PARAMETER :: ind_O1D = 4 
  INTEGER, PARAMETER :: ind_ECH4 = 5 
  INTEGER, PARAMETER :: ind_ETHA = 6 
  INTEGER, PARAMETER :: ind_ETHY = 7 
  INTEGER, PARAMETER :: ind_N2O5 = 8 
  INTEGER, PARAMETER :: ind_BENZ = 9 
  INTEGER, PARAMETER :: ind_EPOX = 10 
  INTEGER, PARAMETER :: ind_ETOH = 11 
  INTEGER, PARAMETER :: ind_PRPA = 12 
  INTEGER, PARAMETER :: ind_KET = 13 
  INTEGER, PARAMETER :: ind_TOL = 14 
  INTEGER, PARAMETER :: ind_XYL = 15 
  INTEGER, PARAMETER :: ind_HPLD = 16 
  INTEGER, PARAMETER :: ind_PAN = 17 
  INTEGER, PARAMETER :: ind_PACD = 18 
  INTEGER, PARAMETER :: ind_NTR2 = 19 
  INTEGER, PARAMETER :: ind_PNA = 20 
  INTEGER, PARAMETER :: ind_MEOH = 21 
  INTEGER, PARAMETER :: ind_HONO = 22 
  INTEGER, PARAMETER :: ind_MEPX = 23 
  INTEGER, PARAMETER :: ind_OPAN = 24 
  INTEGER, PARAMETER :: ind_CAT1 = 25 
  INTEGER, PARAMETER :: ind_H2O2 = 26 
  INTEGER, PARAMETER :: ind_ISPX = 27 
  INTEGER, PARAMETER :: ind_FACD = 28 
  INTEGER, PARAMETER :: ind_PANX = 29 
  INTEGER, PARAMETER :: ind_HCO3 = 30 
  INTEGER, PARAMETER :: ind_CRO = 31 
  INTEGER, PARAMETER :: ind_ROOH = 32 
  INTEGER, PARAMETER :: ind_NTR1 = 33 
  INTEGER, PARAMETER :: ind_ACET = 34 
  INTEGER, PARAMETER :: ind_INTR = 35 
  INTEGER, PARAMETER :: ind_BZO2 = 36 
  INTEGER, PARAMETER :: ind_CRON = 37 
  INTEGER, PARAMETER :: ind_AACD = 38 
  INTEGER, PARAMETER :: ind_ROR = 39 
  INTEGER, PARAMETER :: ind_TO2 = 40 
  INTEGER, PARAMETER :: ind_ETH = 41 
  INTEGER, PARAMETER :: ind_CO = 42 
  INTEGER, PARAMETER :: ind_XLO2 = 43 
  INTEGER, PARAMETER :: ind_TERP = 44 
  INTEGER, PARAMETER :: ind_CRES = 45 
  INTEGER, PARAMETER :: ind_ISOP = 46 
  INTEGER, PARAMETER :: ind_EPX2 = 47 
  INTEGER, PARAMETER :: ind_HNO3 = 48 
  INTEGER, PARAMETER :: ind_GLYD = 49 
  INTEGER, PARAMETER :: ind_GLY = 50 
  INTEGER, PARAMETER :: ind_XOPN = 51 
  INTEGER, PARAMETER :: ind_MGLY = 52 
  INTEGER, PARAMETER :: ind_OPEN = 53 
  INTEGER, PARAMETER :: ind_IOLE = 54 
  INTEGER, PARAMETER :: ind_FORM = 55 
  INTEGER, PARAMETER :: ind_OLE = 56 
  INTEGER, PARAMETER :: ind_ALD2 = 57 
  INTEGER, PARAMETER :: ind_XO2 = 58 
  INTEGER, PARAMETER :: ind_OPO3 = 59 
  INTEGER, PARAMETER :: ind_XO2N = 60 
  INTEGER, PARAMETER :: ind_ISO2 = 61 
  INTEGER, PARAMETER :: ind_XO2H = 62 
  INTEGER, PARAMETER :: ind_ISPD = 63 
  INTEGER, PARAMETER :: ind_MEO2 = 64 
  INTEGER, PARAMETER :: ind_ALDX = 65 
  INTEGER, PARAMETER :: ind_PAR = 66 
  INTEGER, PARAMETER :: ind_O3 = 67 
  INTEGER, PARAMETER :: ind_RO2 = 68 
  INTEGER, PARAMETER :: ind_OH = 69 
  INTEGER, PARAMETER :: ind_HO2 = 70 
  INTEGER, PARAMETER :: ind_CXO3 = 71 
  INTEGER, PARAMETER :: ind_NO3 = 72 
  INTEGER, PARAMETER :: ind_C2O3 = 73 
  INTEGER, PARAMETER :: ind_O = 74 
  INTEGER, PARAMETER :: ind_NO = 75 
  INTEGER, PARAMETER :: ind_NO2 = 76 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_H2O = 77 
  INTEGER, PARAMETER :: ind_H2 = 78 
  INTEGER, PARAMETER :: ind_O2 = 79 
  INTEGER, PARAMETER :: ind_CH4 = 80 
  INTEGER, PARAMETER :: ind_M = 81 
  INTEGER, PARAMETER :: ind_DUMMY = 82 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER, PARAMETER :: indf_H2O = 1 
  INTEGER, PARAMETER :: indf_H2 = 2 
  INTEGER, PARAMETER :: indf_O2 = 3 
  INTEGER, PARAMETER :: indf_CH4 = 4 
  INTEGER, PARAMETER :: indf_M = 5 
  INTEGER, PARAMETER :: indf_DUMMY = 6 

END MODULE mod_cb6_Parameters

